// Generated Zod validator: HostedPage.updatePaymentMethod
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const updatePaymentMethodHostedPageCustomerSchema = z.object({
  id: z.string().max(50),
  vat_number: z.string().max(20).optional(),
  vat_number_prefix: z.string().max(10).optional(),
});
const updatePaymentMethodHostedPageCardSchema = z.object({
  gateway: z
    .enum([
      'chargebee',
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
    ])
    .optional(),
  gateway_account_id: z.string().max(50).optional(),
});
const updatePaymentMethodHostedPageBodySchema = z.looseObject({
  redirect_url: z.string().max(250).optional(),
  cancel_url: z.string().max(250).optional(),
  pass_thru_content: z.string().max(2048).optional(),
  iframe_messaging: z.boolean().default(false).optional(),
  customer: updatePaymentMethodHostedPageCustomerSchema.optional(),
  card: updatePaymentMethodHostedPageCardSchema.optional(),
  embed: z.boolean().default(true).optional(),
});
export { updatePaymentMethodHostedPageBodySchema };
