// Generated Zod validator: Export.transactions
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const transactionsExportIdSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
  not_in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
});
const transactionsExportCustomerIdSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  is_present: z.enum(['true', 'false']).optional(),
  in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
  not_in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
});
const transactionsExportSubscriptionIdSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  is_present: z.enum(['true', 'false']).optional(),
  in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
  not_in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
});
const transactionsExportPaymentSourceIdSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  is_present: z.enum(['true', 'false']).optional(),
  in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
  not_in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
});
const transactionsExportPaymentMethodSchema = z.object({
  is: z
    .enum([
      'card',
      'cash',
      'check',
      'chargeback',
      'bank_transfer',
      'amazon_payments',
      'paypal_express_checkout',
      'direct_debit',
      'alipay',
      'unionpay',
      'apple_pay',
      'wechat_pay',
      'ach_credit',
      'sepa_credit',
      'ideal',
      'google_pay',
      'sofort',
      'bancontact',
      'giropay',
      'dotpay',
      'other',
      'app_store',
      'upi',
      'netbanking_emandates',
      'play_store',
      'custom',
      'boleto',
      'venmo',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'automated_bank_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
  is_not: z
    .enum([
      'card',
      'cash',
      'check',
      'chargeback',
      'bank_transfer',
      'amazon_payments',
      'paypal_express_checkout',
      'direct_debit',
      'alipay',
      'unionpay',
      'apple_pay',
      'wechat_pay',
      'ach_credit',
      'sepa_credit',
      'ideal',
      'google_pay',
      'sofort',
      'bancontact',
      'giropay',
      'dotpay',
      'other',
      'app_store',
      'upi',
      'netbanking_emandates',
      'play_store',
      'custom',
      'boleto',
      'venmo',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'automated_bank_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
  in: z
    .enum([
      'card',
      'cash',
      'check',
      'chargeback',
      'bank_transfer',
      'amazon_payments',
      'paypal_express_checkout',
      'direct_debit',
      'alipay',
      'unionpay',
      'apple_pay',
      'wechat_pay',
      'ach_credit',
      'sepa_credit',
      'ideal',
      'google_pay',
      'sofort',
      'bancontact',
      'giropay',
      'dotpay',
      'other',
      'app_store',
      'upi',
      'netbanking_emandates',
      'play_store',
      'custom',
      'boleto',
      'venmo',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'automated_bank_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
  not_in: z
    .enum([
      'card',
      'cash',
      'check',
      'chargeback',
      'bank_transfer',
      'amazon_payments',
      'paypal_express_checkout',
      'direct_debit',
      'alipay',
      'unionpay',
      'apple_pay',
      'wechat_pay',
      'ach_credit',
      'sepa_credit',
      'ideal',
      'google_pay',
      'sofort',
      'bancontact',
      'giropay',
      'dotpay',
      'other',
      'app_store',
      'upi',
      'netbanking_emandates',
      'play_store',
      'custom',
      'boleto',
      'venmo',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'automated_bank_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
});
const transactionsExportGatewaySchema = z.object({
  is: z
    .enum([
      'chargebee',
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'gocardless',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
      'not_applicable',
    ])
    .optional(),
  is_not: z
    .enum([
      'chargebee',
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'gocardless',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
      'not_applicable',
    ])
    .optional(),
  in: z
    .enum([
      'chargebee',
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'gocardless',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
      'not_applicable',
    ])
    .optional(),
  not_in: z
    .enum([
      'chargebee',
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'gocardless',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
      'not_applicable',
    ])
    .optional(),
});
const transactionsExportGatewayAccountIdSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
  not_in: z.string().regex(RegExp('^[(.*)(,.*)*]$')).optional(),
});
const transactionsExportIdAtGatewaySchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
});
const transactionsExportReferenceNumberSchema = z.object({
  is: z.string().min(1).optional(),
  is_not: z.string().min(1).optional(),
  starts_with: z.string().min(1).optional(),
  is_present: z.enum(['true', 'false']).optional(),
});
const transactionsExportTypeSchema = z.object({
  is: z
    .enum(['authorization', 'payment', 'refund', 'payment_reversal'])
    .optional(),
  is_not: z
    .enum(['authorization', 'payment', 'refund', 'payment_reversal'])
    .optional(),
  in: z
    .enum(['authorization', 'payment', 'refund', 'payment_reversal'])
    .optional(),
  not_in: z
    .enum(['authorization', 'payment', 'refund', 'payment_reversal'])
    .optional(),
});
const transactionsExportDateSchema = z.object({
  after: z.string().regex(RegExp('^d{10}$')).optional(),
  before: z.string().regex(RegExp('^d{10}$')).optional(),
  on: z.string().regex(RegExp('^d{10}$')).optional(),
  between: z.string().regex(RegExp('^[d{10},d{10}]$')).optional(),
});
const transactionsExportAmountSchema = z.object({
  is: z.string().regex(RegExp('^-?d+$')).optional(),
  is_not: z.string().regex(RegExp('^-?d+$')).optional(),
  lt: z.string().regex(RegExp('^-?d+$')).optional(),
  lte: z.string().regex(RegExp('^-?d+$')).optional(),
  gt: z.string().regex(RegExp('^-?d+$')).optional(),
  gte: z.string().regex(RegExp('^-?d+$')).optional(),
  between: z.string().regex(RegExp('^[-?d+,-?d+]$')).optional(),
});
const transactionsExportAmountCapturableSchema = z.object({
  is: z.string().regex(RegExp('^-?d+$')).optional(),
  is_not: z.string().regex(RegExp('^-?d+$')).optional(),
  lt: z.string().regex(RegExp('^-?d+$')).optional(),
  lte: z.string().regex(RegExp('^-?d+$')).optional(),
  gt: z.string().regex(RegExp('^-?d+$')).optional(),
  gte: z.string().regex(RegExp('^-?d+$')).optional(),
  between: z.string().regex(RegExp('^[-?d+,-?d+]$')).optional(),
});
const transactionsExportStatusSchema = z.object({
  is: z
    .enum([
      'in_progress',
      'success',
      'voided',
      'failure',
      'timeout',
      'needs_attention',
      'late_failure',
    ])
    .optional(),
  is_not: z
    .enum([
      'in_progress',
      'success',
      'voided',
      'failure',
      'timeout',
      'needs_attention',
      'late_failure',
    ])
    .optional(),
  in: z
    .enum([
      'in_progress',
      'success',
      'voided',
      'failure',
      'timeout',
      'needs_attention',
      'late_failure',
    ])
    .optional(),
  not_in: z
    .enum([
      'in_progress',
      'success',
      'voided',
      'failure',
      'timeout',
      'needs_attention',
      'late_failure',
    ])
    .optional(),
});
const transactionsExportUpdatedAtSchema = z.object({
  after: z.string().regex(RegExp('^d{10}$')).optional(),
  before: z.string().regex(RegExp('^d{10}$')).optional(),
  on: z.string().regex(RegExp('^d{10}$')).optional(),
  between: z.string().regex(RegExp('^[d{10},d{10}]$')).optional(),
});
const transactionsExportTransactionItemSchema = z.object({
  id: transactionsExportIdSchema.optional(),
  customer_id: transactionsExportCustomerIdSchema.optional(),
  subscription_id: transactionsExportSubscriptionIdSchema.optional(),
  payment_source_id: transactionsExportPaymentSourceIdSchema.optional(),
  payment_method: transactionsExportPaymentMethodSchema.optional(),
  gateway: transactionsExportGatewaySchema.optional(),
  gateway_account_id: transactionsExportGatewayAccountIdSchema.optional(),
  id_at_gateway: transactionsExportIdAtGatewaySchema.optional(),
  reference_number: transactionsExportReferenceNumberSchema.optional(),
  type: transactionsExportTypeSchema.optional(),
  date: transactionsExportDateSchema.optional(),
  amount: transactionsExportAmountSchema.optional(),
  amount_capturable: transactionsExportAmountCapturableSchema.optional(),
  status: transactionsExportStatusSchema.optional(),
  updated_at: transactionsExportUpdatedAtSchema.optional(),
});
const transactionsExportBodySchema = z.looseObject({
  transaction: z
    .array(transactionsExportTransactionItemSchema.optional())
    .optional(),
});
export { transactionsExportBodySchema };
