var _endpoints = {
  "subscription": [
    [
      "create",
      "POST",
      "/subscriptions",
      null,
      false
    ],
    [
      "create_for_customer",
      "POST",
      "/customers",
      "/subscriptions",
      true
    ],
    [
      "list",
      "GET",
      "/subscriptions",
      null,
      false
    ],
    [
      "subscriptions_for_customer",
      "GET",
      "/customers",
      "/subscriptions",
      true
    ],
    [
      "retrieve",
      "GET",
      "/subscriptions",
      null,
      true
    ],
    [
      "retrieve_with_scheduled_changes",
      "GET",
      "/subscriptions",
      "/retrieve_with_scheduled_changes",
      true
    ],
    [
      "remove_scheduled_changes",
      "POST",
      "/subscriptions",
      "/remove_scheduled_changes",
      true
    ],
    [
      "remove_scheduled_cancellation",
      "POST",
      "/subscriptions",
      "/remove_scheduled_cancellation",
      true
    ],
    [
      "remove_coupons",
      "POST",
      "/subscriptions",
      "/remove_coupons",
      true
    ],
    [
      "update",
      "POST",
      "/subscriptions",
      null,
      true
    ],
    [
      "change_term_end",
      "POST",
      "/subscriptions",
      "/change_term_end",
      true
    ],
    [
      "cancel",
      "POST",
      "/subscriptions",
      "/cancel",
      true
    ],
    [
      "reactivate",
      "POST",
      "/subscriptions",
      "/reactivate",
      true
    ],
    [
      "add_charge_at_term_end",
      "POST",
      "/subscriptions",
      "/add_charge_at_term_end",
      true
    ],
    [
      "charge_addon_at_term_end",
      "POST",
      "/subscriptions",
      "/charge_addon_at_term_end",
      true
    ],
    [
      "charge_future_renewals",
      "POST",
      "/subscriptions",
      "/charge_future_renewals",
      true
    ],
    [
      "import_subscription",
      "POST",
      "/subscriptions",
      "/import_subscription",
      false
    ],
    [
      "import_for_customer",
      "POST",
      "/customers",
      "/import_subscription",
      true
    ],
    [
      "override_billing_profile",
      "POST",
      "/subscriptions",
      "/override_billing_profile",
      true
    ],
    [
      "delete",
      "POST",
      "/subscriptions",
      "/delete",
      true
    ]
  ],
  "customer": [
    [
      "create",
      "POST",
      "/customers",
      null,
      false
    ],
    [
      "list",
      "GET",
      "/customers",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/customers",
      null,
      true
    ],
    [
      "update",
      "POST",
      "/customers",
      null,
      true
    ],
    [
      "update_payment_method",
      "POST",
      "/customers",
      "/update_payment_method",
      true
    ],
    [
      "update_billing_info",
      "POST",
      "/customers",
      "/update_billing_info",
      true
    ],
    [
      "assign_payment_role",
      "POST",
      "/customers",
      "/assign_payment_role",
      true
    ],
    [
      "add_contact",
      "POST",
      "/customers",
      "/add_contact",
      true
    ],
    [
      "update_contact",
      "POST",
      "/customers",
      "/update_contact",
      true
    ],
    [
      "delete_contact",
      "POST",
      "/customers",
      "/delete_contact",
      true
    ],
    [
      "add_promotional_credits",
      "POST",
      "/customers",
      "/add_promotional_credits",
      true
    ],
    [
      "deduct_promotional_credits",
      "POST",
      "/customers",
      "/deduct_promotional_credits",
      true
    ],
    [
      "set_promotional_credits",
      "POST",
      "/customers",
      "/set_promotional_credits",
      true
    ],
    [
      "record_excess_payment",
      "POST",
      "/customers",
      "/record_excess_payment",
      true
    ],
    [
      "collect_payment",
      "POST",
      "/customers",
      "/collect_payment",
      true
    ],
    [
      "delete",
      "POST",
      "/customers",
      "/delete",
      true
    ],
    [
      "move",
      "POST",
      "/customers",
      "/move",
      false
    ],
    [
      "change_billing_date",
      "POST",
      "/customers",
      "/change_billing_date",
      true
    ]
  ],
  "payment_source": [
    [
      "create_using_temp_token",
      "POST",
      "/payment_sources",
      "/create_using_temp_token",
      false
    ],
    [
      "create_using_permanent_token",
      "POST",
      "/payment_sources",
      "/create_using_permanent_token",
      false
    ],
    [
      "create_card",
      "POST",
      "/payment_sources",
      "/create_card",
      false
    ],
    [
      "update_card",
      "POST",
      "/payment_sources",
      "/update_card",
      true
    ],
    [
      "retrieve",
      "GET",
      "/payment_sources",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/payment_sources",
      null,
      false
    ],
    [
      "switch_gateway_account",
      "POST",
      "/payment_sources",
      "/switch_gateway_account",
      true
    ],
    [
      "export_payment_source",
      "POST",
      "/payment_sources",
      "/export_payment_source",
      true
    ],
    [
      "delete",
      "POST",
      "/payment_sources",
      "/delete",
      true
    ]
  ],
  "third_party_payment_method": [],
  "card": [
    [
      "retrieve",
      "GET",
      "/cards",
      null,
      true
    ],
    [
      "update_card_for_customer",
      "POST",
      "/customers",
      "/credit_card",
      true
    ],
    [
      "switch_gateway_for_customer",
      "POST",
      "/customers",
      "/switch_gateway",
      true
    ],
    [
      "copy_card_for_customer",
      "POST",
      "/customers",
      "/copy_card",
      true
    ],
    [
      "delete_card_for_customer",
      "POST",
      "/customers",
      "/delete_card",
      true
    ]
  ],
  "promotional_credit": [
    [
      "add",
      "POST",
      "/promotional_credits",
      "/add",
      false
    ],
    [
      "deduct",
      "POST",
      "/promotional_credits",
      "/deduct",
      false
    ],
    [
      "set",
      "POST",
      "/promotional_credits",
      "/set",
      false
    ],
    [
      "list",
      "GET",
      "/promotional_credits",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/promotional_credits",
      null,
      true
    ]
  ],
  "invoice": [
    [
      "create",
      "POST",
      "/invoices",
      null,
      false
    ],
    [
      "charge",
      "POST",
      "/invoices",
      "/charge",
      false
    ],
    [
      "charge_addon",
      "POST",
      "/invoices",
      "/charge_addon",
      false
    ],
    [
      "stop_dunning",
      "POST",
      "/invoices",
      "/stop_dunning",
      true
    ],
    [
      "import_invoice",
      "POST",
      "/invoices",
      "/import_invoice",
      false
    ],
    [
      "apply_payments",
      "POST",
      "/invoices",
      "/apply_payments",
      true
    ],
    [
      "apply_credits",
      "POST",
      "/invoices",
      "/apply_credits",
      true
    ],
    [
      "list",
      "GET",
      "/invoices",
      null,
      false
    ],
    [
      "invoices_for_customer",
      "GET",
      "/customers",
      "/invoices",
      true
    ],
    [
      "invoices_for_subscription",
      "GET",
      "/subscriptions",
      "/invoices",
      true
    ],
    [
      "retrieve",
      "GET",
      "/invoices",
      null,
      true
    ],
    [
      "pdf",
      "POST",
      "/invoices",
      "/pdf",
      true
    ],
    [
      "add_charge",
      "POST",
      "/invoices",
      "/add_charge",
      true
    ],
    [
      "add_addon_charge",
      "POST",
      "/invoices",
      "/add_addon_charge",
      true
    ],
    [
      "close",
      "POST",
      "/invoices",
      "/close",
      true
    ],
    [
      "collect_payment",
      "POST",
      "/invoices",
      "/collect_payment",
      true
    ],
    [
      "record_payment",
      "POST",
      "/invoices",
      "/record_payment",
      true
    ],
    [
      "refund",
      "POST",
      "/invoices",
      "/refund",
      true
    ],
    [
      "record_refund",
      "POST",
      "/invoices",
      "/record_refund",
      true
    ],
    [
      "remove_payment",
      "POST",
      "/invoices",
      "/remove_payment",
      true
    ],
    [
      "remove_credit_note",
      "POST",
      "/invoices",
      "/remove_credit_note",
      true
    ],
    [
      "void_invoice",
      "POST",
      "/invoices",
      "/void",
      true
    ],
    [
      "write_off",
      "POST",
      "/invoices",
      "/write_off",
      true
    ],
    [
      "delete",
      "POST",
      "/invoices",
      "/delete",
      true
    ],
    [
      "update_details",
      "POST",
      "/invoices",
      "/update_details",
      true
    ]
  ],
  "credit_note": [
    [
      "create",
      "POST",
      "/credit_notes",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/credit_notes",
      null,
      true
    ],
    [
      "pdf",
      "POST",
      "/credit_notes",
      "/pdf",
      true
    ],
    [
      "record_refund",
      "POST",
      "/credit_notes",
      "/record_refund",
      true
    ],
    [
      "void_credit_note",
      "POST",
      "/credit_notes",
      "/void",
      true
    ],
    [
      "list",
      "GET",
      "/credit_notes",
      null,
      false
    ],
    [
      "credit_notes_for_customer",
      "GET",
      "/customers",
      "/credit_notes",
      true
    ],
    [
      "delete",
      "POST",
      "/credit_notes",
      "/delete",
      true
    ]
  ],
  "unbilled_charge": [
    [
      "invoice_unbilled_charges",
      "POST",
      "/unbilled_charges",
      "/invoice_unbilled_charges",
      false
    ],
    [
      "delete",
      "POST",
      "/unbilled_charges",
      "/delete",
      true
    ],
    [
      "list",
      "GET",
      "/unbilled_charges",
      null,
      false
    ],
    [
      "invoice_now_estimate",
      "POST",
      "/unbilled_charges",
      "/invoice_now_estimate",
      false
    ]
  ],
  "order": [
    [
      "create",
      "POST",
      "/orders",
      null,
      false
    ],
    [
      "update",
      "POST",
      "/orders",
      null,
      true
    ],
    [
      "retrieve",
      "GET",
      "/orders",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/orders",
      null,
      false
    ],
    [
      "orders_for_invoice",
      "GET",
      "/invoices",
      "/orders",
      true
    ]
  ],
  "transaction": [
    [
      "list",
      "GET",
      "/transactions",
      null,
      false
    ],
    [
      "transactions_for_customer",
      "GET",
      "/customers",
      "/transactions",
      true
    ],
    [
      "transactions_for_subscription",
      "GET",
      "/subscriptions",
      "/transactions",
      true
    ],
    [
      "payments_for_invoice",
      "GET",
      "/invoices",
      "/payments",
      true
    ],
    [
      "retrieve",
      "GET",
      "/transactions",
      null,
      true
    ]
  ],
  "hosted_page": [
    [
      "checkout_new",
      "POST",
      "/hosted_pages",
      "/checkout_new",
      false
    ],
    [
      "checkout_existing",
      "POST",
      "/hosted_pages",
      "/checkout_existing",
      false
    ],
    [
      "update_card",
      "POST",
      "/hosted_pages",
      "/update_card",
      false
    ],
    [
      "update_payment_method",
      "POST",
      "/hosted_pages",
      "/update_payment_method",
      false
    ],
    [
      "manage_payment_sources",
      "POST",
      "/hosted_pages",
      "/manage_payment_sources",
      false
    ],
    [
      "collect_now",
      "POST",
      "/hosted_pages",
      "/collect_now",
      false
    ],
    [
      "acknowledge",
      "POST",
      "/hosted_pages",
      "/acknowledge",
      true
    ],
    [
      "retrieve",
      "GET",
      "/hosted_pages",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/hosted_pages",
      null,
      false
    ]
  ],
  "estimate": [
    [
      "create_subscription",
      "POST",
      "/estimates",
      "/create_subscription",
      false
    ],
    [
      "create_sub_for_customer_estimate",
      "GET",
      "/customers",
      "/create_subscription_estimate",
      true
    ],
    [
      "update_subscription",
      "POST",
      "/estimates",
      "/update_subscription",
      false
    ],
    [
      "renewal_estimate",
      "GET",
      "/subscriptions",
      "/renewal_estimate",
      true
    ],
    [
      "upcoming_invoices_estimate",
      "GET",
      "/customers",
      "/upcoming_invoices_estimate",
      true
    ],
    [
      "change_term_end",
      "POST",
      "/subscriptions",
      "/change_term_end_estimate",
      true
    ],
    [
      "cancel_subscription",
      "POST",
      "/subscriptions",
      "/cancel_subscription_estimate",
      true
    ]
  ],
  "plan": [
    [
      "create",
      "POST",
      "/plans",
      null,
      false
    ],
    [
      "update",
      "POST",
      "/plans",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/plans",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/plans",
      null,
      true
    ],
    [
      "delete",
      "POST",
      "/plans",
      "/delete",
      true
    ],
    [
      "copy",
      "POST",
      "/plans",
      "/copy",
      false
    ],
    [
      "unarchive",
      "POST",
      "/plans",
      "/unarchive",
      true
    ]
  ],
  "addon": [
    [
      "create",
      "POST",
      "/addons",
      null,
      false
    ],
    [
      "update",
      "POST",
      "/addons",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/addons",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/addons",
      null,
      true
    ],
    [
      "delete",
      "POST",
      "/addons",
      "/delete",
      true
    ],
    [
      "copy",
      "POST",
      "/addons",
      "/copy",
      false
    ],
    [
      "unarchive",
      "POST",
      "/addons",
      "/unarchive",
      true
    ]
  ],
  "coupon": [
    [
      "create",
      "POST",
      "/coupons",
      null,
      false
    ],
    [
      "list",
      "GET",
      "/coupons",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/coupons",
      null,
      true
    ],
    [
      "delete",
      "POST",
      "/coupons",
      "/delete",
      true
    ],
    [
      "copy",
      "POST",
      "/coupons",
      "/copy",
      false
    ],
    [
      "unarchive",
      "POST",
      "/coupons",
      "/unarchive",
      true
    ]
  ],
  "coupon_set": [
    [
      "create",
      "POST",
      "/coupon_sets",
      null,
      false
    ],
    [
      "add_coupon_codes",
      "POST",
      "/coupon_sets",
      "/add_coupon_codes",
      true
    ],
    [
      "list",
      "GET",
      "/coupon_sets",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/coupon_sets",
      null,
      true
    ],
    [
      "update",
      "POST",
      "/coupon_sets",
      "/update",
      true
    ],
    [
      "delete",
      "POST",
      "/coupon_sets",
      "/delete",
      true
    ],
    [
      "delete_unused_coupon_codes",
      "POST",
      "/coupon_sets",
      "/delete_unused_coupon_codes",
      true
    ]
  ],
  "coupon_code": [
    [
      "create",
      "POST",
      "/coupon_codes",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/coupon_codes",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/coupon_codes",
      null,
      false
    ],
    [
      "archive",
      "POST",
      "/coupon_codes",
      "/archive",
      true
    ]
  ],
  "address": [
    [
      "retrieve",
      "GET",
      "/addresses",
      null,
      false
    ],
    [
      "update",
      "POST",
      "/addresses",
      null,
      false
    ]
  ],
  "event": [
    [
      "list",
      "GET",
      "/events",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/events",
      null,
      true
    ]
  ],
  "comment": [
    [
      "create",
      "POST",
      "/comments",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/comments",
      null,
      true
    ],
    [
      "list",
      "GET",
      "/comments",
      null,
      false
    ],
    [
      "delete",
      "POST",
      "/comments",
      "/delete",
      true
    ]
  ],
  "download": [],
  "portal_session": [
    [
      "create",
      "POST",
      "/portal_sessions",
      null,
      false
    ],
    [
      "retrieve",
      "GET",
      "/portal_sessions",
      null,
      true
    ],
    [
      "logout",
      "POST",
      "/portal_sessions",
      "/logout",
      true
    ],
    [
      "activate",
      "POST",
      "/portal_sessions",
      "/activate",
      true
    ]
  ],
  "site_migration_detail": [[
    "list",
    "GET",
    "/site_migration_details",
    null,
    false
  ]],
  "resource_migration": [[
    "retrieve_latest",
    "GET",
    "/resource_migrations",
    "/retrieve_latest",
    false
  ]],
  "time_machine": [
    [
      "retrieve",
      "GET",
      "/time_machines",
      null,
      true
    ],
    [
      "start_afresh",
      "POST",
      "/time_machines",
      "/start_afresh",
      true
    ],
    [
      "travel_forward",
      "POST",
      "/time_machines",
      "/travel_forward",
      true
    ]
  ]
};
module.exports = _endpoints;