declare module 'chargebee' {
  export class RequestConfig {
    site ?: string
    api_key ?: string
    timeout ?: number
    timemachineWaitInMillis ?: number
    exportWaitInMillis ?: number
  }
  export class ChargebeeRequest<T> {
    setIdempotencyKey(idempotencyKey: string): this;
    request(config ?: RequestConfig): Promise<T>;
    headers(headers : {[key : string] : string}): this;
  }
  type AccountHolderType = 'individual' | 'company'
  type AccountReceivablesHandling = 'schedule_payment_collection' | 'no_action' | 'write_off'
  type AccountType = 'checking' | 'current' | 'savings' | 'business_checking'
  type Action = 'upsert' | 'remove'
  type ApiVersion = 'v1' | 'v2'
  type ApplyOn = 'specific_item_price' | 'invoice_amount'
  type AutoCollection = 'off' | 'on'
  type AvalaraSaleType = 'consumed' | 'wholesale' | 'vendor_use' | 'retail'
  type BillingAlignmentMode = 'immediate' | 'delayed'
  type BillingDateMode = 'manually_set' | 'using_defaults'
  type BillingDayOfWeekMode = 'manually_set' | 'using_defaults'
  type ChangeOption = 'immediately' | 'specific_date'
  type Channel = 'app_store' | 'web' | 'play_store'
  type ChargeModel = 'full_charge' | 'prorate'
  type ChargeOnEvent = 'subscription_creation' | 'subscription_activation' | 'subscription_trial_start' | 'contract_termination' | 'plan_activation' | 'on_demand'
  type ChargeOnOption = 'on_event' | 'immediately'
  type ChargesHandling = 'add_to_unbilled_charges' | 'invoice_immediately'
  type ContractTermCancelOption = 'end_of_contract_term' | 'terminate_immediately'
  type CreditOptionForCurrentTermCharges = 'none' | 'prorate' | 'full'
  type CreditType = 'general' | 'loyalty_credits' | 'referral_rewards'
  type CustomerType = 'industrial' | 'residential' | 'business' | 'senior_citizen'
  type DedupeOption = 'update_existing' | 'skip'
  type DispositionType = 'attachment' | 'inline'
  type DunningType = 'offline' | 'auto_collect' | 'direct_debit'
  type DurationType = 'limited_period' | 'one_time' | 'forever'
  type EcheckType = 'web' | 'ppd' | 'ccd'
  type EinvoicingMethod = 'automatic' | 'manual' | 'site_default'
  type EndScheduleOn = 'after_number_of_intervals' | 'specific_date' | 'subscription_end'
  type EntityCode = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'p' | 'q' | 'r' | 'med2' | 'med1'
  type EntityType = 'item' | 'product' | 'coupon' | 'addon' | 'item_price' | 'business_entity' | 'subscription' | 'item_family' | 'credit_note' | 'quote' | 'variant' | 'invoice' | 'plan' | 'transaction' | 'customer' | 'order' | 'price_variant'
  type EventName = 'cancellation_page_loaded'
  type EventType = 'coupon_created' | 'coupon_updated' | 'coupon_deleted' | 'coupon_set_created' | 'coupon_set_updated' | 'coupon_set_deleted' | 'coupon_codes_added' | 'coupon_codes_deleted' | 'coupon_codes_updated' | 'customer_created' | 'customer_changed' | 'customer_deleted' | 'customer_moved_out' | 'customer_moved_in' | 'promotional_credits_added' | 'promotional_credits_deducted' | 'subscription_created' | 'subscription_created_with_backdating' | 'subscription_started' | 'subscription_trial_end_reminder' | 'subscription_activated' | 'subscription_activated_with_backdating' | 'subscription_changed' | 'subscription_trial_extended' | 'mrr_updated' | 'subscription_changed_with_backdating' | 'subscription_cancellation_scheduled' | 'subscription_cancellation_reminder' | 'subscription_cancelled' | 'subscription_canceled_with_backdating' | 'subscription_reactivated' | 'subscription_reactivated_with_backdating' | 'subscription_renewed' | 'subscription_scheduled_cancellation_removed' | 'subscription_changes_scheduled' | 'subscription_scheduled_changes_removed' | 'subscription_shipping_address_updated' | 'subscription_deleted' | 'subscription_paused' | 'subscription_pause_scheduled' | 'subscription_scheduled_pause_removed' | 'subscription_resumed' | 'subscription_resumption_scheduled' | 'subscription_scheduled_resumption_removed' | 'subscription_advance_invoice_schedule_added' | 'subscription_advance_invoice_schedule_updated' | 'subscription_advance_invoice_schedule_removed' | 'pending_invoice_created' | 'pending_invoice_updated' | 'invoice_generated' | 'invoice_generated_with_backdating' | 'invoice_updated' | 'invoice_deleted' | 'credit_note_created' | 'credit_note_created_with_backdating' | 'credit_note_updated' | 'credit_note_deleted' | 'invoice_installments_created' | 'invoice_installment_updated' | 'installment_config_created' | 'installment_config_deleted' | 'subscription_renewal_reminder' | 'add_usages_reminder' | 'transaction_created' | 'transaction_updated' | 'transaction_deleted' | 'payment_succeeded' | 'payment_failed' | 'payment_refunded' | 'payment_initiated' | 'refund_initiated' | 'authorization_succeeded' | 'authorization_voided' | 'card_added' | 'card_updated' | 'card_expiry_reminder' | 'card_expired' | 'card_deleted' | 'payment_source_added' | 'payment_source_updated' | 'payment_source_deleted' | 'payment_source_expiring' | 'payment_source_expired' | 'payment_source_locally_deleted' | 'virtual_bank_account_added' | 'virtual_bank_account_updated' | 'virtual_bank_account_deleted' | 'token_created' | 'token_consumed' | 'token_expired' | 'unbilled_charges_created' | 'unbilled_charges_voided' | 'unbilled_charges_deleted' | 'unbilled_charges_invoiced' | 'order_created' | 'order_updated' | 'order_cancelled' | 'order_delivered' | 'order_returned' | 'order_ready_to_process' | 'order_ready_to_ship' | 'order_deleted' | 'order_resent' | 'quote_created' | 'quote_updated' | 'quote_deleted' | 'tax_withheld_recorded' | 'tax_withheld_deleted' | 'tax_withheld_refunded' | 'gift_scheduled' | 'gift_unclaimed' | 'gift_claimed' | 'gift_expired' | 'gift_cancelled' | 'gift_updated' | 'hierarchy_created' | 'hierarchy_deleted' | 'payment_intent_created' | 'payment_intent_updated' | 'contract_term_created' | 'contract_term_renewed' | 'contract_term_terminated' | 'contract_term_completed' | 'contract_term_cancelled' | 'item_family_created' | 'item_family_updated' | 'item_family_deleted' | 'item_created' | 'item_updated' | 'item_deleted' | 'item_price_created' | 'item_price_updated' | 'item_price_deleted' | 'attached_item_created' | 'attached_item_updated' | 'attached_item_deleted' | 'differential_price_created' | 'differential_price_updated' | 'differential_price_deleted' | 'feature_created' | 'feature_updated' | 'feature_deleted' | 'feature_activated' | 'feature_reactivated' | 'feature_archived' | 'item_entitlements_updated' | 'entitlement_overrides_updated' | 'entitlement_overrides_removed' | 'item_entitlements_removed' | 'entitlement_overrides_auto_removed' | 'subscription_entitlements_created' | 'business_entity_created' | 'business_entity_updated' | 'business_entity_deleted' | 'customer_business_entity_changed' | 'subscription_business_entity_changed' | 'purchase_created' | 'voucher_created' | 'voucher_expired' | 'voucher_create_failed' | 'item_price_entitlements_updated' | 'item_price_entitlements_removed' | 'ramp_created' | 'ramp_deleted' | 'ramp_applied' | 'price_variant_created' | 'price_variant_updated' | 'price_variant_deleted'
  type ExportType = 'data' | 'import_friendly_data'
  type FreePeriodUnit = 'week' | 'month' | 'year' | 'day'
  type FriendOfferType = 'coupon_code' | 'coupon' | 'none'
  type Gateway = 'bluepay' | 'beanstream' | 'elavon' | 'orbital' | 'hdfc' | 'nmi' | 'moneris' | 'metrics_global' | 'ebanx' | 'pin' | 'stripe' | 'quickbooks' | 'razorpay' | 'eway_rapid' | 'balanced_payments' | 'ecentric' | 'wepay' | 'chargebee_payments' | 'bank_of_america' | 'braintree' | 'first_data_global' | 'paypal_express_checkout' | 'ingenico_direct' | 'moneris_us' | 'exact' | 'migs' | 'checkout_com' | 'not_applicable' | 'paypal_pro' | 'ogone' | 'eway' | 'dlocal' | 'gocardless' | 'global_payments' | 'paymill' | 'adyen' | 'paypal' | 'chargebee' | 'authorize_net' | 'tco' | 'bluesnap' | 'windcave' | 'paypal_payflow_pro' | 'amazon_payments' | 'mollie' | 'cybersource' | 'wirecard' | 'sage_pay' | 'vantiv' | 'worldpay' | 'pay_com'
  type HierarchyOperationType = 'complete_hierarchy' | 'subordinates' | 'path_to_root'
  type InvoiceDunningHandling = 'stop' | 'continue'
  type ItemType = 'charge' | 'addon' | 'plan'
  type Layout = 'in_app' | 'full_page'
  type NotifyReferralSystem = 'all_invoices' | 'none' | 'first_paid_conversion'
  type OfflinePaymentMethod = 'eu_automated_bank_transfer' | 'bank_transfer' | 'mx_automated_bank_transfer' | 'custom' | 'ach_credit' | 'boleto' | 'check' | 'uk_automated_bank_transfer' | 'no_preference' | 'us_automated_bank_transfer' | 'jp_automated_bank_transfer' | 'sepa_credit' | 'cash'
  type OnEvent = 'subscription_creation' | 'subscription_activation' | 'subscription_trial_start' | 'contract_termination' | 'plan_activation'
  type Operation = 'create' | 'update' | 'delete'
  type OperationType = 'add' | 'remove'
  type PauseOption = 'end_of_term' | 'billing_cycles' | 'immediately' | 'specific_date'
  type PaymentInitiator = 'merchant' | 'customer'
  type PaymentMethod = 'other' | 'netbanking_emandates' | 'klarna_pay_now' | 'ach_credit' | 'dotpay' | 'boleto' | 'direct_debit' | 'automated_bank_transfer' | 'chargeback' | 'wechat_pay' | 'pay_to' | 'cash' | 'giropay' | 'bank_transfer' | 'alipay' | 'ideal' | 'sepa_instant_transfer' | 'google_pay' | 'custom' | 'unionpay' | 'check' | 'faster_payments' | 'sofort' | 'amazon_payments' | 'upi' | 'venmo' | 'apple_pay' | 'bancontact' | 'paypal_express_checkout' | 'sepa_credit' | 'card'
  type PaymentMethodType = 'giropay' | 'alipay' | 'ideal' | 'sepa_instant_transfer' | 'google_pay' | 'netbanking_emandates' | 'klarna_pay_now' | 'dotpay' | 'unionpay' | 'direct_debit' | 'faster_payments' | 'generic' | 'sofort' | 'amazon_payments' | 'upi' | 'venmo' | 'apple_pay' | 'bancontact' | 'automated_bank_transfer' | 'paypal_express_checkout' | 'wechat_pay' | 'pay_to' | 'card'
  type PaymentVoucherType = 'boleto'
  type PeriodUnit = 'week' | 'month' | 'year' | 'day'
  type PriceType = 'tax_exclusive' | 'tax_inclusive'
  type PricingModel = 'volume' | 'per_unit' | 'tiered' | 'flat_fee' | 'stairstep'
  type ProrationType = 'partial_term' | 'full_term' | 'none'
  type ReferralSystem = 'referral_candy' | 'friendbuy' | 'referral_saasquatch'
  type ReferrerRewardType = 'custom_promotional_credit' | 'referral_direct_reward' | 'custom_revenue_percent_based' | 'none'
  type RefundableCreditsHandling = 'schedule_refund' | 'no_action'
  type ReportBy = 'product' | 'invoice' | 'subscription' | 'customer'
  type ResumeOption = 'immediately' | 'specific_date'
  type Role = 'backup' | 'none' | 'primary'
  type ScheduleType = 'immediate' | 'specific_dates' | 'fixed_intervals'
  type Source = 'admin_console' | 'system' | 'scheduled_job' | 'js_api' | 'bulk_operation' | 'hosted_page' | 'migration' | 'api' | 'none' | 'portal' | 'external_service'
  type TaxExemptReason = 'high_value_physical_goods' | 'tax_not_configured' | 'reverse_charge' | 'zero_rated' | 'tax_not_configured_external_provider' | 'customer_exempt' | 'region_non_taxable' | 'zero_value_item' | 'export' | 'product_exempt'
  type TaxJurisType = 'special' | 'country' | 'unincorporated' | 'other' | 'city' | 'federal' | 'county' | 'state'
  type TaxOverrideReason = 'id_exempt' | 'customer_exempt' | 'export'
  type Taxability = 'taxable' | 'exempt'
  type TaxjarExemptionCategory = 'other' | 'wholesale' | 'government'
  type TrialEndAction = 'activate_subscription' | 'plan_default' | 'cancel_subscription' | 'site_default'
  type Type = 'giropay' | 'alipay' | 'ideal' | 'sepa_instant_transfer' | 'google_pay' | 'netbanking_emandates' | 'klarna_pay_now' | 'dotpay' | 'unionpay' | 'direct_debit' | 'faster_payments' | 'generic' | 'sofort' | 'amazon_payments' | 'upi' | 'venmo' | 'apple_pay' | 'bancontact' | 'automated_bank_transfer' | 'paypal_express_checkout' | 'wechat_pay' | 'pay_to' | 'card'
  type UnbilledChargesHandling = 'invoice' | 'no_action'
  type UnbilledChargesOption = 'invoice' | 'delete'
  type UnpaidInvoicesHandling = 'schedule_payment_collection' | 'no_action'
  type ValidationStatus = 'valid' | 'partially_valid' | 'invalid' | 'not_validated'
  type VoucherType = 'boleto'
  
}