/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

export {
  CHARGEBEE_SDK_NAME,
  CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX,
  CHARGEBEE_TELEMETRY_HEADER_PREFIX,
  HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX,
  TELEMETRY_SPAN_NAME_PREFIX,
  TelemetryAttributeKeys,
  type BuildRequestTelemetryContextInput,
  type RequestTelemetryContext,
  type RequestTelemetryError,
  type RequestTelemetryHandle,
  type RequestTelemetryResult,
} from './types.js';

export {
  NO_OP_TELEMETRY_ADAPTER,
  NoOpTelemetryAdapter,
  type RequestHeadersForTelemetry,
  type TelemetryAdapter,
  buildRequestEndSpanAttributes,
  buildRequestHeaderSpanAttributes,
  buildRequestStartSpanAttributes,
  buildRequestTelemetryContext,
  buildRequestTelemetryResult,
  buildSpanName,
  extractHttpStatusCode,
  extractRequestTelemetryError,
  resolveChargebeeApiVersion,
} from './TelemetryAdapter.js';
