/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

export {
  CHARGEBEE_SDK_NAME,
  CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX,
  CHARGEBEE_TELEMETRY_HEADER_PREFIX,
  CHARGEBEE_TELEMETRY_PREFER_HEADER,
  CHARGEBEE_TELEMETRY_PREFER_VALUE,
  HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX,
  HTTP_RESPONSE_HEADER_ATTRIBUTE_PREFIX,
  TELEMETRY_SPAN_NAME_PREFIX,
  TelemetryAttributeKeys,
  X_CHARGEBEE_TELEMETRY_HEADER,
  type BuildRequestTelemetryContextInput,
  type RequestTelemetryContext,
  type RequestTelemetryEndAttributeValue,
  type RequestTelemetryError,
  type RequestTelemetryHandle,
  type RequestTelemetryResult,
  type ResponseHeadersForTelemetry,
} from './types.js';

export {
  parseChargebeeTelemetryHeaderToSpanAttributes,
  type ChargebeeTelemetrySpanAttributes,
} from './chargebeeTelemetryHeaderParser.js';

export {
  NO_OP_TELEMETRY_ADAPTER,
  NoOpTelemetryAdapter,
  type RequestHeadersForTelemetry,
  type TelemetryAdapter,
  buildRequestEndSpanAttributes,
  buildRequestHeaderSpanAttributes,
  buildRequestStartSpanAttributes,
  buildRequestTelemetryContext,
  buildRequestTelemetryResult,
  buildResponseHeaderSpanAttributes,
  buildSpanName,
  applyResponseTelemetryPreferHeader,
  extractHttpStatusCode,
  extractRequestTelemetryError,
  extractResponseHeaders,
  getResponseHeaderValueIgnoreCase,
  resolveChargebeeApiVersion,
} from './TelemetryAdapter.js';
