/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/** Constants for the anonymous SDK telemetry request header. */
export const SDK_TELEMETRY_HEADER_NAME = 'x-chargebee-sdk-telemetry';

/** Server drops larger values, so the SDK omits the header rather than sending a truncated one. */
export const SDK_TELEMETRY_MAX_HEADER_BYTES = 4096;

export const SDK_TELEMETRY_REQUEST_ID_HEADER = 'chargebee-request-id';
export const SDK_TELEMETRY_RUNTIME = 'nodejs';
export const SDK_TELEMETRY_SEGMENT = 'sdk';

export const SDK_TELEMETRY_FT_TELEMETRY_ADAPTER = 'ft-telemetry_adapter';
export const SDK_TELEMETRY_FT_CUSTOM_TRANSPORT = 'ft-custom_transport';
export const SDK_TELEMETRY_FT_RETRY_CONFIG = 'ft-retry_config';
