/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/** Immutable snapshot of a completed SDK API call for N+1 header emission. */
export type SdkTelemetrySnapshot = {
  sdkName: string;
  sdkVersion: string;
  resource: string;
  operation: string;
  startTimeEpochSeconds: number;
  timeMs: number;
  httpStatus?: number;
  errorCode?: string;
  requestId?: string;
  featureTokens: string[];
};
