/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

import type { TelemetryAdapter } from './TelemetryAdapter.js';
import { buildSdkTelemetryHeader } from './sdkTelemetryHeaderBuilder.js';
import { SdkTelemetryFeature } from './sdkTelemetryFeature.js';
import { SDK_TELEMETRY_HEADER_NAME } from './sdkTelemetryHeader.js';
import type { SdkTelemetryState } from './sdkTelemetryState.js';

/** Client env fields needed to emit SDK telemetry. */
export type SdkTelemetryEnv = {
  sdkTelemetryEnabled?: boolean;
  sdkTelemetryState?: SdkTelemetryState;
  telemetryAdapter?: TelemetryAdapter;
  httpClientIsCustom?: boolean;
  retryConfig?: { enabled?: boolean };
};

/** Mutable request-header map used when attaching the telemetry header. */
export type RequestHeadersForSdkTelemetry = Record<string, string | number>;

/**
 * Emits the anonymous SDK telemetry request header, independently of any customer telemetry
 * adapter.
 *
 * On the first API call of a client instance, attaches {@code f;…} with enabled feature codes when
 * any are present; omits the header when none are enabled. Later calls on the same client never
 * attach again. SDK identity is correlated via User-Agent. Every failure path is swallowed and
 * logged at WARNING: telemetry must never fail an API call.
 */
export function attachSdkTelemetryHeader(
  env: SdkTelemetryEnv,
  headers: RequestHeadersForSdkTelemetry,
): void {
  if (env.sdkTelemetryEnabled === false) {
    return;
  }

  try {
    if (!env.sdkTelemetryState?.tryMarkEmitted()) {
      return;
    }
    const headerValue = buildSdkTelemetryHeader(resolveFeatures(env));
    if (!headerValue) {
      return;
    }
    headers[SDK_TELEMETRY_HEADER_NAME] = headerValue;
  } catch (err) {
    logSuppressed('attach header', err);
  }
}

/** Collects enabled feature codes for the current client configuration. */
function resolveFeatures(env: SdkTelemetryEnv): SdkTelemetryFeature[] {
  const features: SdkTelemetryFeature[] = [];
  if (env.telemetryAdapter !== undefined) {
    features.push(SdkTelemetryFeature.TELEMETRY_ADAPTER);
  }
  if (env.httpClientIsCustom) {
    features.push(SdkTelemetryFeature.CUSTOM_TRANSPORT);
  }
  if (isRetryConfigActive(env)) {
    features.push(SdkTelemetryFeature.RETRY_CONFIG);
  }
  return features;
}

/** Whether retries are enabled on the client. */
function isRetryConfigActive(env: SdkTelemetryEnv): boolean {
  return env.retryConfig?.enabled === true;
}

/** Logs a suppressed telemetry failure without affecting the API call. */
function logSuppressed(step: string, err: unknown): void {
  const message = err instanceof Error ? err.message : String(err);
  console.warn(
    `SDK telemetry could not ${step} (${message}); API call unaffected.`,
    err,
  );
}
