/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

import { SdkTelemetryFeature } from './sdkTelemetryFeature.js';
import {
  SDK_TELEMETRY_FEATURES_KEY,
  SDK_TELEMETRY_MAX_HEADER_BYTES,
} from './sdkTelemetryHeader.js';

/**
 * Builds RFC 9651 values for {@link SDK_TELEMETRY_HEADER_NAME}: a features segment keyed by
 * {@link SDK_TELEMETRY_FEATURES_KEY} with enabled feature codes as boolean params
 * (for example {@code f;ta;rc}). Correlate SDK identity via User-Agent.
 */
export function buildSdkTelemetryHeader(
  features: ReadonlyArray<SdkTelemetryFeature> | undefined,
): string | undefined {
  if (!features || features.length === 0) {
    return undefined;
  }

  let value = SDK_TELEMETRY_FEATURES_KEY;
  for (const feature of features) {
    if (feature == null) {
      continue;
    }
    value += `;${feature}`;
  }

  if (value.length === SDK_TELEMETRY_FEATURES_KEY.length) {
    return undefined;
  }

  if (new TextEncoder().encode(value).length > SDK_TELEMETRY_MAX_HEADER_BYTES) {
    return undefined;
  }
  return value;
}
