/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/** Constants for the anonymous SDK telemetry request header. */
export const SDK_TELEMETRY_HEADER_NAME = 'x-chargebee-sdk-telemetry';

/** Defensive size cap; feature-only values are tiny. */
export const SDK_TELEMETRY_MAX_HEADER_BYTES = 4096;

/** RFC 9651 sf-list item name for the features segment. */
export const SDK_TELEMETRY_FEATURES_KEY = 'f';
