/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/**
 * Per-client gate so the SDK telemetry header is considered at most once per client instance.
 *
 * Internal SDK type: applications must not depend on it. It is public only so that the
 * Chargebee client can own one instance.
 */
export class SdkTelemetryState {
  private emitted = false;

  /**
   * Claims the single emission slot for this client. Returns true only for the first caller.
   */
  tryMarkEmitted(): boolean {
    if (this.emitted) {
      return false;
    }
    this.emitted = true;
    return true;
  }

  /** Whether this client has already considered emitting the telemetry header. */
  hasEmitted(): boolean {
    return this.emitted;
  }

  /** Clears the emission gate (tests only). */
  clear(): void {
    this.emitted = false;
  }
}
