/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/**
 * SDK configuration features reported under the {@code f} segment of
 * {@link SDK_TELEMETRY_HEADER_NAME}. Wire codes are maintained in sdk-generator.
 */
export enum SdkTelemetryFeature {
  /** Customer TelemetryAdapter configured. */
  TELEMETRY_ADAPTER = 'ta',

  /** Custom HTTP client configured. */
  CUSTOM_TRANSPORT = 'ct',

  /** Retries enabled on the client. */
  RETRY_CONFIG = 'rc',
}
