/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

import type { SdkTelemetrySnapshot } from './sdkTelemetrySnapshot.js';

/**
 * Per-client holder for the last completed call, used by the N+1 SDK telemetry header.
 *
 * Internal SDK type: applications must not depend on it. It is public only so that the
 * Chargebee client can own one instance.
 */
export class SdkTelemetryState {
  private lastCallSnapshot: SdkTelemetrySnapshot | undefined;

  lastCall(): SdkTelemetrySnapshot | undefined {
    return this.lastCallSnapshot;
  }

  record(snapshot: SdkTelemetrySnapshot): void {
    this.lastCallSnapshot = snapshot;
  }

  clear(): void {
    this.lastCallSnapshot = undefined;
  }
}
