/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

import {
  BuildRequestTelemetryContextInput,
  CHARGEBEE_SDK_NAME,
  RequestTelemetryContext,
  RequestTelemetryError,
  RequestTelemetryHandle,
  RequestTelemetryResult,
  TELEMETRY_SPAN_NAME_PREFIX,
  TelemetryAttributeKeys,
} from './types.js';

export type RequestHeadersForTelemetry = Record<string, string | number>;

/**
 * Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
 * When not configured, the SDK skips all telemetry work — zero overhead.
 * Implement as a class or plain object; the SDK stores the adapter by reference.
 */
export interface TelemetryAdapter<THandle = RequestTelemetryHandle> {
  onRequestStart(
    context: RequestTelemetryContext,
    requestHeaders: RequestHeadersForTelemetry,
  ): THandle | void;
  onRequestEnd(handle: THandle | void, result: RequestTelemetryResult): void;
}

export class NoOpTelemetryAdapter implements TelemetryAdapter {
  onRequestStart(): void {
    return;
  }

  onRequestEnd(): void {
    return;
  }
}

export const NO_OP_TELEMETRY_ADAPTER = new NoOpTelemetryAdapter();

export function buildSpanName(resource: string, operation: string): string {
  return `${TELEMETRY_SPAN_NAME_PREFIX}.${resource}.${operation}`;
}

export function resolveChargebeeApiVersion(apiPath: string): 'v1' | 'v2' {
  return apiPath === '/api/v1' ? 'v1' : 'v2';
}

export function buildRequestStartSpanAttributes(
  input: BuildRequestTelemetryContextInput,
): Record<string, string> {
  return {
    [TelemetryAttributeKeys.URL_FULL]: input.httpUrl,
    [TelemetryAttributeKeys.HTTP_REQUEST_METHOD]: input.httpMethod,
    [TelemetryAttributeKeys.SERVER_ADDRESS]: input.serverAddress,
    [TelemetryAttributeKeys.CHARGEBEE_SITE]: input.chargebeeSite,
    [TelemetryAttributeKeys.CHARGEBEE_API_VERSION]: input.chargebeeApiVersion,
    [TelemetryAttributeKeys.CHARGEBEE_RESOURCE]: input.resource,
    [TelemetryAttributeKeys.CHARGEBEE_OPERATION]: input.operation,
    [TelemetryAttributeKeys.CHARGEBEE_SDK_NAME]: CHARGEBEE_SDK_NAME,
    [TelemetryAttributeKeys.CHARGEBEE_SDK_VERSION]: input.sdkVersion,
  };
}

export function buildRequestEndSpanAttributes(
  result: Omit<RequestTelemetryResult, 'endAttributes'>,
): Record<string, string | number> {
  const attributes: Record<string, string | number> = {
    [TelemetryAttributeKeys.HTTP_RESPONSE_STATUS_CODE]: result.httpStatusCode,
  };

  if (result.error) {
    // error.type is the status code on failed requests
    attributes[TelemetryAttributeKeys.ERROR_TYPE] = String(
      result.httpStatusCode,
    );

    if (result.error.chargebeeErrorCode) {
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_CODE] =
        result.error.chargebeeErrorCode;
    }
    if (result.error.chargebeeApiErrorType) {
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_TYPE] =
        result.error.chargebeeApiErrorType;
    }
    if (result.error.chargebeeErrorParam) {
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_PARAM] =
        result.error.chargebeeErrorParam;
    }
  }

  return attributes;
}

export function buildRequestTelemetryContext(
  input: BuildRequestTelemetryContextInput,
): RequestTelemetryContext {
  return {
    spanName: buildSpanName(input.resource, input.operation),
    resource: input.resource,
    operation: input.operation,
    httpMethod: input.httpMethod,
    httpUrl: input.httpUrl,
    serverAddress: input.serverAddress,
    chargebeeSite: input.chargebeeSite,
    chargebeeApiVersion: input.chargebeeApiVersion,
    sdkName: CHARGEBEE_SDK_NAME,
    sdkVersion: input.sdkVersion,
    startAttributes: buildRequestStartSpanAttributes(input),
  };
}

export function buildRequestTelemetryResult(
  result: Omit<RequestTelemetryResult, 'endAttributes'>,
): RequestTelemetryResult {
  return {
    ...result,
    endAttributes: buildRequestEndSpanAttributes(result),
  };
}

export function extractRequestTelemetryError(
  err: unknown,
): RequestTelemetryError | undefined {
  if (err == null || typeof err !== 'object') {
    if (err instanceof Error) {
      return { message: err.message };
    }
    return undefined;
  }

  const errorObj = err as Record<string, unknown>;
  const message =
    typeof errorObj.message === 'string'
      ? errorObj.message
      : err instanceof Error
        ? err.message
        : 'Chargebee API request failed';

  const result: RequestTelemetryError = { message };

  if (typeof errorObj.api_error_code === 'string') {
    result.chargebeeErrorCode = errorObj.api_error_code;
  }
  if (typeof errorObj.type === 'string') {
    result.chargebeeApiErrorType = errorObj.type;
  }
  if (typeof errorObj.param === 'string') {
    result.chargebeeErrorParam = errorObj.param;
  }

  return result;
}

export function extractHttpStatusCode(err: unknown): number | undefined {
  if (err == null || typeof err !== 'object') {
    return undefined;
  }
  const errorObj = err as Record<string, unknown>;
  for (const key of [
    'http_status_code',
    'httpStatusCode',
    'http_code',
    'statusCode',
  ]) {
    const value = errorObj[key];
    if (typeof value === 'number') {
      return value;
    }
  }
  return undefined;
}
