/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

import { parseChargebeeTelemetryHeaderToSpanAttributes } from './chargebeeTelemetryHeaderParser.js';
import {
  BuildRequestTelemetryContextInput,
  CHARGEBEE_SDK_NAME,
  CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX,
  CHARGEBEE_TELEMETRY_HEADER_PREFIX,
  CHARGEBEE_TELEMETRY_PREFER_HEADER,
  CHARGEBEE_TELEMETRY_PREFER_VALUE,
  HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX,
  HTTP_RESPONSE_HEADER_ATTRIBUTE_PREFIX,
  RequestTelemetryContext,
  RequestTelemetryEndAttributeValue,
  RequestTelemetryError,
  RequestTelemetryHandle,
  RequestTelemetryResult,
  ResponseHeadersForTelemetry,
  TELEMETRY_SPAN_NAME_PREFIX,
  TelemetryAttributeKeys,
  X_CHARGEBEE_TELEMETRY_HEADER,
} from './types.js';

export type RequestHeadersForTelemetry = Record<string, string | number>;

/**
 * Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
 * When not configured, the SDK skips all telemetry work — zero overhead.
 * Implement as a class or plain object; the SDK stores the adapter by reference.
 */
export interface TelemetryAdapter<THandle = RequestTelemetryHandle> {
  onRequestStart(
    context: RequestTelemetryContext,
    requestHeaders: RequestHeadersForTelemetry,
  ): THandle | void;
  onRequestEnd(handle: THandle | void, result: RequestTelemetryResult): void;
}

export class NoOpTelemetryAdapter implements TelemetryAdapter {
  onRequestStart(): void {
    return;
  }

  onRequestEnd(): void {
    return;
  }
}

export const NO_OP_TELEMETRY_ADAPTER = new NoOpTelemetryAdapter();

export function buildSpanName(resource: string, operation: string): string {
  return `${TELEMETRY_SPAN_NAME_PREFIX}.${resource}.${operation}`;
}

export function resolveChargebeeApiVersion(apiPath: string): 'v1' | 'v2' {
  return apiPath === '/api/v1' ? 'v1' : 'v2';
}

/**
 * Adds {@code Prefer: chargebee-telemetry=include} when not already set.
 * Chargebee returns {@code X-Chargebee-Telemetry} only when this header is present.
 */
export function applyResponseTelemetryPreferHeader(
  requestHeaders: Record<string, string | number>,
): void {
  const preferHeader = CHARGEBEE_TELEMETRY_PREFER_HEADER.toLowerCase();
  for (const name of Object.keys(requestHeaders)) {
    if (name != null && name.toLowerCase() === preferHeader) {
      return;
    }
  }
  requestHeaders[CHARGEBEE_TELEMETRY_PREFER_HEADER] =
    CHARGEBEE_TELEMETRY_PREFER_VALUE;
}

/**
 * Captures Chargebee custom request headers as OTel span attributes.
 *
 * Headers whose (lowercased) name starts with `chargebee-` are recorded as
 * `http.request.header.<name>` with string[] values, per the OpenTelemetry HTTP semantic
 * conventions. The `chargebee-request-origin-*` family (origin IP, email, device) is skipped
 * because it carries end-user PII. Matching by prefix means new `chargebee-*` headers are
 * captured automatically without an SDK upgrade.
 */
export function buildRequestHeaderSpanAttributes(
  requestHeaders: Record<string, string | number> | undefined,
): Record<string, string[]> {
  const attributes: Record<string, string[]> = {};
  if (!requestHeaders) {
    return attributes;
  }

  for (const [name, value] of Object.entries(requestHeaders)) {
    if (name == null || value === undefined || value === null) {
      continue;
    }
    const lowerName = name.toLowerCase();
    if (
      !lowerName.startsWith(CHARGEBEE_TELEMETRY_HEADER_PREFIX) ||
      lowerName.startsWith(CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX)
    ) {
      continue;
    }
    attributes[`${HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX}${lowerName}`] = [
      String(value),
    ];
  }

  return attributes;
}

/** Case-insensitive response header lookup; skips entries whose name is null/undefined. */
export function getResponseHeaderValueIgnoreCase(
  headers: Record<string, string | string[] | number | undefined> | undefined,
  headerName: string,
): string | undefined {
  if (!headers) {
    return undefined;
  }
  const target = headerName.toLowerCase();
  for (const [name, value] of Object.entries(headers)) {
    if (name == null || value === undefined || value === null) {
      continue;
    }
    if (name.toLowerCase() === target) {
      return Array.isArray(value) ? value.join(', ') : String(value);
    }
  }
  return undefined;
}

/**
 * Captures the {@code X-Chargebee-Telemetry} response header as OpenTelemetry span attributes.
 */
export function buildResponseHeaderSpanAttributes(
  responseHeaders: ResponseHeadersForTelemetry | undefined,
): Record<string, RequestTelemetryEndAttributeValue> {
  const attributes: Record<string, RequestTelemetryEndAttributeValue> = {};
  if (!responseHeaders) {
    return attributes;
  }

  const value = getResponseHeaderValueIgnoreCase(
    responseHeaders,
    X_CHARGEBEE_TELEMETRY_HEADER,
  );
  if (value != null) {
    attributes[
      `${HTTP_RESPONSE_HEADER_ATTRIBUTE_PREFIX}${X_CHARGEBEE_TELEMETRY_HEADER}`
    ] = value;
    Object.assign(
      attributes,
      parseChargebeeTelemetryHeaderToSpanAttributes(value),
    );
  }

  return attributes;
}

export function buildRequestStartSpanAttributes(
  input: BuildRequestTelemetryContextInput,
): Record<string, string | string[]> {
  return {
    [TelemetryAttributeKeys.URL_FULL]: input.httpUrl,
    [TelemetryAttributeKeys.HTTP_REQUEST_METHOD]: input.httpMethod,
    [TelemetryAttributeKeys.SERVER_ADDRESS]: input.serverAddress,
    [TelemetryAttributeKeys.CHARGEBEE_SITE]: input.chargebeeSite,
    [TelemetryAttributeKeys.CHARGEBEE_API_VERSION]: input.chargebeeApiVersion,
    [TelemetryAttributeKeys.CHARGEBEE_RESOURCE]: input.resource,
    [TelemetryAttributeKeys.CHARGEBEE_OPERATION]: input.operation,
    [TelemetryAttributeKeys.CHARGEBEE_SDK_NAME]: CHARGEBEE_SDK_NAME,
    [TelemetryAttributeKeys.CHARGEBEE_SDK_VERSION]: input.sdkVersion,
    ...buildRequestHeaderSpanAttributes(input.requestHeaders),
  };
}

export function buildRequestEndSpanAttributes(
  result: Omit<RequestTelemetryResult, 'endAttributes'>,
): Record<string, RequestTelemetryEndAttributeValue> {
  const attributes: Record<string, RequestTelemetryEndAttributeValue> = {
    [TelemetryAttributeKeys.HTTP_RESPONSE_STATUS_CODE]: result.httpStatusCode,
    ...buildResponseHeaderSpanAttributes(result.responseHeaders),
  };

  if (result.error) {
    if (result.error.chargebeeApiErrorType) {
      attributes[TelemetryAttributeKeys.ERROR_TYPE] =
        result.error.chargebeeApiErrorType;
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_TYPE] =
        result.error.chargebeeApiErrorType;
    }

    if (result.error.chargebeeErrorCode) {
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_CODE] =
        result.error.chargebeeErrorCode;
    }
    if (result.error.chargebeeErrorParam) {
      attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_PARAM] =
        result.error.chargebeeErrorParam;
    }
  }

  return attributes;
}

export function buildRequestTelemetryContext(
  input: BuildRequestTelemetryContextInput,
): RequestTelemetryContext {
  return {
    spanName: buildSpanName(input.resource, input.operation),
    resource: input.resource,
    operation: input.operation,
    httpMethod: input.httpMethod,
    httpUrl: input.httpUrl,
    serverAddress: input.serverAddress,
    chargebeeSite: input.chargebeeSite,
    chargebeeApiVersion: input.chargebeeApiVersion,
    sdkName: CHARGEBEE_SDK_NAME,
    sdkVersion: input.sdkVersion,
    startAttributes: buildRequestStartSpanAttributes(input),
  };
}

export function buildRequestTelemetryResult(
  result: Omit<RequestTelemetryResult, 'endAttributes'>,
): RequestTelemetryResult {
  return {
    ...result,
    endAttributes: buildRequestEndSpanAttributes(result),
  };
}

export function extractRequestTelemetryError(
  err: unknown,
): RequestTelemetryError | undefined {
  if (err == null || typeof err !== 'object') {
    if (err instanceof Error) {
      return { message: err.message };
    }
    return undefined;
  }

  const errorObj = err as Record<string, unknown>;
  const message =
    typeof errorObj.message === 'string'
      ? errorObj.message
      : err instanceof Error
        ? err.message
        : 'Chargebee API request failed';

  const result: RequestTelemetryError = { message };

  if (typeof errorObj.api_error_code === 'string') {
    result.chargebeeErrorCode = errorObj.api_error_code;
  }
  if (typeof errorObj.type === 'string') {
    result.chargebeeApiErrorType = errorObj.type;
  }
  if (typeof errorObj.param === 'string') {
    result.chargebeeErrorParam = errorObj.param;
  }

  return result;
}

export function extractHttpStatusCode(err: unknown): number | undefined {
  if (err == null || typeof err !== 'object') {
    return undefined;
  }
  const errorObj = err as Record<string, unknown>;
  for (const key of [
    'http_status_code',
    'httpStatusCode',
    'http_code',
    'statusCode',
  ]) {
    const value = errorObj[key];
    if (typeof value === 'number') {
      return value;
    }
  }
  return undefined;
}

export function extractResponseHeaders(
  err: unknown,
): ResponseHeadersForTelemetry | undefined {
  if (err == null || typeof err !== 'object') {
    return undefined;
  }

  const errorObj = err as Record<string, unknown>;
  const response = errorObj.response;
  if (response != null && typeof response === 'object') {
    const headers = (response as Record<string, unknown>).headers;
    if (headers != null && typeof headers === 'object') {
      return headers as ResponseHeadersForTelemetry;
    }
  }

  const headers = errorObj.headers;
  if (headers != null && typeof headers === 'object') {
    return headers as ResponseHeadersForTelemetry;
  }

  return undefined;
}
