/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

/** SDK identifier recorded on telemetry spans. */
export const CHARGEBEE_SDK_NAME = 'chargebee-node';

/** Standard span name prefix: chargebee.{resource}.{operation} */
export const TELEMETRY_SPAN_NAME_PREFIX = 'chargebee';

/** Span attribute keys — shared across Chargebee SDKs. */
export const TelemetryAttributeKeys = {
  URL_FULL: 'url.full',
  HTTP_REQUEST_METHOD: 'http.request.method',
  HTTP_RESPONSE_STATUS_CODE: 'http.response.status_code',
  SERVER_ADDRESS: 'server.address',
  ERROR_TYPE: 'error.type',
  CHARGEBEE_SITE: 'chargebee.site',
  CHARGEBEE_API_VERSION: 'chargebee.api_version',
  CHARGEBEE_RESOURCE: 'chargebee.resource',
  CHARGEBEE_OPERATION: 'chargebee.operation',
  CHARGEBEE_SDK_NAME: 'chargebee.sdk.name',
  CHARGEBEE_SDK_VERSION: 'chargebee.sdk.version',
  CHARGEBEE_ERROR_CODE: 'chargebee.error.code',
  CHARGEBEE_ERROR_TYPE: 'chargebee.error.type',
  CHARGEBEE_ERROR_PARAM: 'chargebee.error.param',
} as const;

export type RequestTelemetryHandle = unknown;

export type RequestTelemetryContext = {
  spanName: string;
  resource: string;
  operation: string;
  httpMethod: string;
  httpUrl: string;
  serverAddress: string;
  chargebeeSite: string;
  chargebeeApiVersion: 'v1' | 'v2';
  sdkName: typeof CHARGEBEE_SDK_NAME;
  sdkVersion: string;
  /** Prebuilt span attributes — pass these to your tracer. */
  startAttributes: Record<string, string>;
};

export type RequestTelemetryError = {
  message: string;
  chargebeeErrorCode?: string;
  chargebeeApiErrorType?: string;
  chargebeeErrorParam?: string;
};

export type RequestTelemetryResult = {
  httpStatusCode: number;
  durationMs: number;
  error?: RequestTelemetryError;
  /** Prebuilt span attributes — pass these to your tracer. */
  endAttributes: Record<string, string | number>;
};

export type BuildRequestTelemetryContextInput = {
  resource: string;
  operation: string;
  httpMethod: string;
  httpUrl: string;
  serverAddress: string;
  chargebeeSite: string;
  chargebeeApiVersion: 'v1' | 'v2';
  sdkVersion: string;
};
