///<reference path='./../core.d.ts'/>
declare module 'chargebee' {
  export interface Address {
    
    /**
      * @description Label to identify the address. This is unique for all the address for a subscription.

      */
    
    label:string;
    
    /**
      * @description First name

      */
    
    first_name?:string;
    
    /**
      * @description Last name

      */
    
    last_name?:string;
    
    /**
      * @description Email

      */
    
    email?:string;
    
    /**
      * @description Company name

      */
    
    company?:string;
    
    /**
      * @description Phone number

      */
    
    phone?:string;
    
    /**
      * @description Address line 1

      */
    
    addr?:string;
    
    /**
      * @description Address line 2

      */
    
    extended_addr?:string;
    
    /**
      * @description Address line 3

      */
    
    extended_addr2?:string;
    
    /**
      * @description Name of the city

      */
    
    city?:string;
    
    /**
      * @description The [ISO 3166-2 state/province code](https://www.iso.org/obp/ui/#search) without the country prefix. Currently supported for USA, Canada and India. For instance, for Arizona (USA), set &#x60;state_code&#x60; as &#x60;AZ&#x60; (not &#x60;US-AZ&#x60;). For Tamil Nadu (India), set as &#x60;TN&#x60; (not &#x60;IN-TN&#x60;). For British Columbia (Canada), set as &#x60;BC&#x60; (not &#x60;CA-BC&#x60;).

      */
    
    state_code?:string;
    
    /**
      * @description State or Province

      */
    
    state?:string;
    
    /**
      * @description The billing address country of the customer. Must be one of [ISO 3166 alpha-2 country code](https://www.iso.org/iso-3166-country-codes.html).   

**Note** : If you enter an invalid country code, the system will return an error.  

**Brexit**


If you have enabled [EU VAT](https://www.chargebee.com/docs/eu-vat.html) in 2021 or later, or have [manually enable](https://www.chargebee.com/docs/brexit.html#what-needs-to-be-done-in-chargebee) the Brexit configuration, then &#x60;XI&#x60; (the code for **United Kingdom -- Northern Ireland**) is available as an option.

      */
    
    country?:string;
    
    /**
      * @description Zip or postal code. The number of characters is validated according to the rules [specified here](https://chromium-i18n.appspot.com/ssl-address).

      */
    
    zip?:string;
    
    /**
      * @description The address verification status. \* partially_valid - The address is valid for taxability but has not been validated for shipping. \* not_validated - Address is not yet validated. \* invalid - Address is invalid. \* valid - Address was validated successfully.

      */
    
    validation_status?:ValidationStatus;
    
    /**
      * @description A unique and immutable identifier for the subscription. If not provided, it is autogenerated.

      */
    
    subscription_id:string;
  }
  export namespace Address {
    export class AddressResource {  
      /**
        * @description Retrieves an address resource for a subscription and the specified label.

        */
      
      retrieve(input:RetrieveInputParam):ChargebeeRequest<RetrieveResponse>;
       
      /**
        * @description Adds or replaces the address for a subscription. If an address is already present for the specified label, it will be replaced otherwise new address is added with that label.

        */
      
      update(input:UpdateInputParam):ChargebeeRequest<UpdateResponse>;
    }
    export interface RetrieveResponse {  
       address:Address;
    }
    export interface RetrieveInputParam {
       
      /**
        * @description Retrieves an address resource for a subscription and the specified label.

        */
        
      subscription_id:string;
       
      /**
        * @description Retrieves an address resource for a subscription and the specified label.

        */
        
      label:string;
    }
    export interface UpdateResponse {  
       address:Address;
    }
    export interface UpdateInputParam {
       
      /**
        * @description A unique and immutable identifier for the subscription. If not provided, it is autogenerated.

        */
       
      subscription_id:string;
       
      /**
        * @description Label to identify the address. This is unique for all the address for a subscription.

        */
       
      label:string;
       
      /**
        * @description First name.

        */
       
      first_name?:string;
       
      /**
        * @description Last name.

        */
       
      last_name?:string;
       
      /**
        * @description Email.

        */
       
      email?:string;
       
      /**
        * @description Company name.

        */
       
      company?:string;
       
      /**
        * @description Phone number.

        */
       
      phone?:string;
       
      /**
        * @description Address line 1.

        */
       
      addr?:string;
       
      /**
        * @description Address line 2.

        */
       
      extended_addr?:string;
       
      /**
        * @description Address line 3.

        */
       
      extended_addr2?:string;
       
      /**
        * @description Name of the city.

        */
       
      city?:string;
       
      /**
        * @description The [ISO 3166-2 state/province code](https://www.iso.org/obp/ui/#search/code) without the country prefix. Currently supported for USA, Canada and India. For instance, for Arizona (USA), set &#x60;state_code&#x60; as &#x60;AZ&#x60; (not &#x60;US-AZ&#x60;). For Tamil Nadu (India), set as &#x60;TN&#x60; (not &#x60;IN-TN&#x60;). For British Columbia (Canada), set as &#x60;BC&#x60; (not &#x60;CA-BC&#x60;).

        */
       
      state_code?:string;
       
      /**
        * @description The state/province name. Is set by Chargebee automatically for US, Canada and India If &#x60;state_code&#x60; is provided.

        */
       
      state?:string;
       
      /**
        * @description Zip or postal code. The number of characters is validated according to the rules [specified here](https://chromium-i18n.appspot.com/ssl-address).

        */
       
      zip?:string;
       
      /**
        * @description The billing address country of the customer. Must be one of [ISO 3166 alpha-2 country code](https://www.iso.org/iso-3166-country-codes.html).   

**Note** : If you enter an invalid country code, the system will return an error.  

**Brexit**


If you have enabled [EU VAT](https://www.chargebee.com/docs/eu-vat.html) in 2021 or later, or have [manually enable](https://www.chargebee.com/docs/brexit.html#what-needs-to-be-done-in-chargebee) the Brexit configuration, then &#x60;XI&#x60; (the code for **United Kingdom -- Northern Ireland**) is available as an option.
.

        */
       
      country?:string;
       
      /**
        * @description The address verification status. \* partially_valid - The address is valid for taxability but has not been validated for shipping. \* not_validated - Address is not yet validated. \* invalid - Address is invalid. \* valid - Address was validated successfully.

        */
       
      validation_status?:ValidationStatus;
    }
    
  }
}