///<reference path='./../core.d.ts'/>
declare module 'chargebee' {
  export interface Media {
    
    /**
      * @description The unique identifier for the media file. This is auto-generated by Chargebee.

      */
    
    id:string;
    
    /**
      * @description The public URL for accessing the media file. This is auto-generated by Chargebee.

      */
    
    url?:string;
    
    /**
      * @description The [alternative text](https://webaim.org/techniques/alttext/) for the image. Applicable only when the top-level &#x60;media_type&#x60; is &#x60;image&#x60;.

      */
    
    alt_text?:string;
    
    /**
      * @description The [media type](https://en.wikipedia.org/wiki/Media_type) of the file.

      */
    
    media_type?:string;
  }
}