///<reference path='./../core.d.ts'/>
declare module 'chargebee' {
  export interface Order {
    
    /**
      * @description Uniquely identifies the order. It is the api identifier for the order

      */
    
    id:string;
    
    /**
      * @description The order&#x27;s serial number

      */
    
    document_number?:string;
    
    /**
      * @description The invoice number which acts as an identifier for invoice and is generated sequentially.

      */
    
    invoice_id?:string;
    
    /**
      * @description The subscription for which the order is created

      */
    
    subscription_id?:string;
    
    /**
      * @description The customer for which the order is created

      */
    
    customer_id?:string;
    
    /**
      * @description The status of this order. \* complete - Order has been processed successfully. Applicable only if you are using Chargebee&#x27;s legacy order management system \* partially_delivered - The order has been partially delivered to the customer. \* voided - Order has been voided. Applicable only if you are using Chargebee&#x27;s legacy order management system \* on_hold - The order is paused from being processed. \* awaiting_shipment - The order has been picked up by an integration system, and synced to a shipping management platform \* shipped - The order has moved from order management system to a shipping system. \* queued - Order is yet to be processed by any system, these are scheduled orders created by Chargebee \* new - Order has been created. Applicable only if you are using Chargebee&#x27;s legacy order management system. \* returned - The order has been returned after delivery. \* delivered - The order has been delivered to the customer. \* cancelled - Order has been cancelled. Applicable only if you are using Chargebee&#x27;s legacy order management system \* processing - Order is being processed. Applicable only if you are using Chargebee&#x27;s legacy order management system

      */
    
    status?:'new' | 'partially_delivered' | 'queued' | 'delivered' | 'on_hold' | 'shipped' | 'processing' | 'cancelled' | 'voided' | 'complete' | 'awaiting_shipment' | 'returned';
    
    /**
      * @description Cancellation reason \* payment_declined - Payment declined. \* shipping_cut_off_passed - The invoice has been paid late and Chargebee cancel&#x27;s the first order for the invoice. \* product_not_available - Product not available. \* alternative_found - Alternative found. \* others - Other reason \* order_resent - Order resent \* product_unsatisfactory - Product unsatisfactory. \* delivery_date_missed - Delivery date missed. \* fraudulent_transaction - Fraudulent transaction. \* invoice_voided - The invoice for which the order was createed has been voided. \* subscription_cancelled - The subsctiption for which the order was created has been cancelled. \* invoice_written_off - The invoice has been completely written off. Orders are generated by Chargebee in cancelled state. \* product_not_required - Product not required. \* third_party_cancellation - Third party cancellation.

      */
    
    cancellation_reason?:'delivery_date_missed' | 'subscription_cancelled' | 'product_unsatisfactory' | 'fraudulent_transaction' | 'third_party_cancellation' | 'order_resent' | 'payment_declined' | 'product_not_required' | 'invoice_voided' | 'invoice_written_off' | 'product_not_available' | 'shipping_cut_off_passed' | 'others' | 'alternative_found';
    
    /**
      * @description The payment status of the order \* paid - PAID \* not_paid - NOT_PAID

      */
    
    payment_status?:'paid' | 'not_paid';
    
    /**
      * @description Order type \* manual - The order has been created by the the user using Chargebee&#x27;s legacy order management system. \* system_generated - The order has been created by Chargebee automatically based on the preferences set by the user.

      */
    
    order_type?:'system_generated' | 'manual';
    
    /**
      * @description The price type of the order \* tax_inclusive - All amounts in the document are inclusive of tax. \* tax_exclusive - All amounts in the document are exclusive of tax.

      */
    
    price_type:PriceType;
    
    /**
      * @description Reference id can be used to map the orders in the shipping/order management application to the orders in ChargeBee. The reference_id generally is same as the order id in the third party application.

      */
    
    reference_id?:string;
    
    /**
      * @description The fulfillment status of an order as reflected in the shipping/order management application. Typical statuses include Shipped,Awaiting Shipment,Not fulfilled etc;

      */
    
    fulfillment_status?:string;
    
    /**
      * @description The date on which the order will start getting processed.

      */
    
    order_date?:number;
    
    /**
      * @description This is the date on which the order will be delivered to the customer.

      */
    
    shipping_date?:number;
    
    /**
      * @description The custom note for the order.

      */
    
    note?:string;
    
    /**
      * @description The tracking id of the order.

      */
    
    tracking_id?:string;
    
    /**
      * @description The tracking url of the order.

      */
    
    tracking_url?:string;
    
    /**
      * @description Unique id to identify a group of orders.

      */
    
    batch_id?:string;
    
    /**
      * @description The source (or the user) from where the order has been created.

      */
    
    created_by?:string;
    
    /**
      * @description Shipment carrier

      */
    
    shipment_carrier?:string;
    
    /**
      * @description The total round off taken from the invoice level

      */
    
    invoice_round_off_amount?:number;
    
    /**
      * @description The total tax for the order.

      */
    
    tax?:number;
    
    /**
      * @description Total amount paid for the order.

      */
    
    amount_paid?:number;
    
    /**
      * @description Total amount adjusted for the order.

      */
    
    amount_adjusted?:number;
    
    /**
      * @description The total amount issued as credits on behalf of this order.

      */
    
    refundable_credits_issued?:number;
    
    /**
      * @description The total amount that can be issued as credits for this order.

      */
    
    refundable_credits?:number;
    
    /**
      * @description Rounding adjustment

      */
    
    rounding_adjustement?:number;
    
    /**
      * @description The timestamp indicating the date \&amp; time the order&#x27;s invoice got paid.

      */
    
    paid_on?:number;
    
    /**
      * @description The time after which an order becomes unservicable

      */
    
    shipping_cut_off_date?:number;
    
    /**
      * @description The time at which the order was created

      */
    
    created_at:number;
    
    /**
      * @description The time at which the order status was last updated.

      */
    
    status_update_at?:number;
    
    /**
      * @description The time at which the order was delivered

      */
    
    delivered_at?:number;
    
    /**
      * @description The time at which the order was shipped.

      */
    
    shipped_at?:number;
    
    /**
      * @description Version number of this resource. The &#x60;resource_version&#x60; is updated with a new timestamp in milliseconds for every change made to the resource. This attribute will be present only if the resource has been updated after 2016-09-28.

      */
    
    resource_version?:number;
    
    /**
      * @description The order&#x27;s last modified time.

      */
    
    updated_at?:number;
    
    /**
      * @description The time at which the order was cancelled.

      */
    
    cancelled_at?:number;
    
    /**
      * @description Resent status of the order. \* fully_resent - Order is Fully resent \* partially_resent - Order is Partially resent

      */
    
    resent_status?:'fully_resent' | 'partially_resent';
    
    /**
      * @description Show if the order is resent order or not.

      */
    
    is_resent:boolean;
    
    /**
      * @description Refers to the original order id of the resent order.

      */
    
    original_order_id?:string;
    
    /**
      * @description Total discount given for the order.

      */
    
    discount?:number;
    
    /**
      * @description The order&#x27;s sub-total

      */
    
    sub_total?:number;
    
    /**
      * @description Total amount charged for the order.

      */
    
    total?:number;
    
    /**
      * @description Indicates that this resource has been deleted.

      */
    
    deleted:boolean;
    
    /**
      * @description The currency code (ISO 4217 format) for the invoice

      */
    
    currency_code?:string;
    
    /**
      * @description Boolean indicating whether this order is gifted or not.

      */
    
    is_gifted?:boolean;
    
    /**
      * @description The gift message added by the gifter during purchase

      */
    
    gift_note?:string;
    
    /**
      * @description The gift_id if the order is a gift order

      */
    
    gift_id?:string;
    
    /**
      * @description Reason code for resending the order. Must be one from a list of reason codes set in the Chargebee app in **Settings \&gt; Configure Chargebee \&gt; Reason Codes \&gt; Orders \&gt; Order Resend**. Must be passed if set as mandatory in the app. The codes are case-sensitive

      */
    
    resend_reason?:string;
    
    /**
      * @description The unique ID of the [business entity](/docs/api/advanced-features?prod_cat_ver&#x3D;2#mbe) of this subscription. This is always the same as the [business entity](/docs/api/subscriptions?prod_cat_ver&#x3D;2#subscription_customer_id) of the customer.

      */
    
    business_entity_id?:string;
    
    /**
      * @description The list of line items for this order.

      */
    
    order_line_items?:Order.OrderLineItem[];
    
    /**
      * @description Shipping address for the order.

      */
    
    shipping_address?:Order.ShippingAddress;
    
    /**
      * @description Billing address for the order.

      */
    
    billing_address?:Order.BillingAddress;
    
    /**
      * @description The list of taxes applied on the order line items.

      */
    
    line_item_taxes?:Order.LineItemTax[];
    
    /**
      * @description The list of discounts applied for the order

      */
    
    line_item_discounts?:Order.LineItemDiscount[];
    
    /**
      * @description The credit notes linked to the order

      */
    
    linked_credit_notes?:Order.OrderLineItemLinkedCredit[];
    
    /**
      * @description The list of resent orders applied on the order.

      */
    
    resent_orders?:Order.ResentOrder[];
  }
  export namespace Order {
    export class OrderResource {  
      /**
        * @description This API is used to retrieve a list of all the available orders.

        */
      
      list(input?:ListInputParam):ChargebeeRequest<ListResponse>;
       
      /**
        * @description #### Deprecated

Chargebee no longer supports this endpoint, see [here](https://www.chargebee.com/docs/1.0/manual_orders_deprecate.html) for more information. Contact [Support](https://chargebee.freshdesk.com/support/home/) for additional assistance or if you have concerns about this update.

        */
      
      create(input:CreateInputParam):ChargebeeRequest<CreateResponse>;
       
      /**
        * @description Import an order for an invoice with one or more line items. The import order bulk operation is to be applied on an imported invoice.

        */
      
      import_order(input:ImportOrderInputParam):ChargebeeRequest<ImportOrderResponse>;
       
      /**
        * @description Assigns order number to the order based on the settings, if not already assigned

        */
      
      assign_order_number(order_id:string):ChargebeeRequest<AssignOrderNumberResponse>;
       
      /**
        * @description Resend an existing order. This will help in resending an existing order in full or partial. Upto 5 resend operations are allowed per . When resent fully, the original order is canceled.

        */
      
      resend(order_id:string, input?:ResendInputParam):ChargebeeRequest<ResendResponse>;
       
      /**
        * @description This API is used to re-open a cancelled order

        */
      
      reopen(order_id:string, input?:ReopenInputParam):ChargebeeRequest<ReopenResponse>;
       
      /**
        * @description Cancel order and create a refundable credit note for the order

        */
      
      cancel(order_id:string, input:CancelInputParam):ChargebeeRequest<CancelResponse>;
       
      /**
        * @description Retrieves an order corresponding to the order id passed.

        */
      
      retrieve(order_id:string):ChargebeeRequest<RetrieveResponse>;
       
      /**
        * @description Updates an order. If the status of an order is changed while updating the order, the status_update_at attribute is set with the current time.

        */
      
      update(order_id:string, input?:UpdateInputParam):ChargebeeRequest<UpdateResponse>;
       
      /**
        * @description Deletes only [Imported Order](#import_an_order) .Delete does not happen if the order was refunded. It goes through if order refund was initiated and is in &quot;refund_due&quot; state.

        */
      
      delete(order_id:string):ChargebeeRequest<DeleteResponse>;
       
      /**
        * @description This API is used to create a refundable credit note for the order

        */
      
      create_refundable_credit_note(order_id:string, input?:CreateRefundableCreditNoteInputParam):ChargebeeRequest<CreateRefundableCreditNoteResponse>;
    }
    export interface ListResponse {  
      /**
        * @description This API is used to retrieve a list of all the available orders.

        */
       
       list:{order:Order}[];
       
      /**
        * @description This API is used to retrieve a list of all the available orders.

        */
       
       next_offset?:string;
    }
    export interface ListInputParam {
      [key : string]: any;  
      /**
        * @description The number of resources to be returned.

        */
        
      limit?:number;
       
      /**
        * @description Determines your position in the list for pagination. To ensure that the next page is retrieved correctly, always set \&#x60;offset\&#x60; to the value of \&#x60;next_offset\&#x60; obtained in the previous iteration of the API call.

        */
        
      offset?:string;
       
      /**
        * @description Indicates whether to include deleted objects in the list. The deleted objects have the attribute \&#x60;deleted\&#x60; as \&#x60;true\&#x60;.

        */
        
      include_deleted?:boolean;
       
      /**
        * @description This API is used to retrieve a list of all the available orders.

        */
        
      exclude_deleted_credit_notes?:boolean;
       
      /**
        * @description Uniquely identifies the order. It is the api identifier for the order

        */
        
      id?:{in?:string,is?:string,is_not?:string,not_in?:string,starts_with?:string};
       
      /**
        * @description The invoice number which acts as an identifier for invoice and is generated sequentially.

        */
        
      invoice_id?:{in?:string,is?:string,is_not?:string,not_in?:string,starts_with?:string};
       
      /**
        * @description The subscription for which the order is created

        */
        
      subscription_id?:{is?:string,is_not?:string,starts_with?:string};
       
      /**
        * @description The status of this order.

        */
        
      status?:{in?:string,is?:'new' | 'partially_delivered' | 'queued' | 'delivered' | 'on_hold' | 'shipped' | 'processing' | 'cancelled' | 'voided' | 'complete' | 'awaiting_shipment' | 'returned',is_not?:'new' | 'partially_delivered' | 'queued' | 'delivered' | 'on_hold' | 'shipped' | 'processing' | 'cancelled' | 'voided' | 'complete' | 'awaiting_shipment' | 'returned',not_in?:string};
       
      /**
        * @description This is the date on which the order will be delivered to the customer.

        */
        
      shipping_date?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description The time at which the order was shipped.

        */
        
      shipped_at?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description Order type

        */
        
      order_type?:{in?:string,is?:'system_generated' | 'manual',is_not?:'system_generated' | 'manual',not_in?:string};
       
      /**
        * @description The date on which the order will start getting processed.

        */
        
      order_date?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description The timestamp indicating the date \&amp; time the order&#x27;s invoice got paid.

        */
        
      paid_on?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description To filter based on updated at .

        */
        
      updated_at?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description The time at which the order was created

        */
        
      created_at?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description Resent order status.

        */
        
      resent_status?:{in?:string,is?:'fully_resent' | 'partially_resent',is_not?:'fully_resent' | 'partially_resent',not_in?:string};
       
      /**
        * @description Order is resent order or not.

        */
        
      is_resent?:{is?:'true' | 'false'};
       
      /**
        * @description If resent order what is the parent order id.

        */
        
      original_order_id?:{is?:string,is_not?:string,starts_with?:string};
       
      /**
        * @description This API is used to retrieve a list of all the available orders.

        */
        
      sort_by?:{asc?:'updated_at' | 'created_at',desc?:'updated_at' | 'created_at'};
    }
    export interface CreateResponse {  
       order:Order;
    }
    export interface CreateInputParam {
       
      /**
        * @description Uniquely identifies the order. If not given, this will be auto-generated.

        */
       
      id?:string;
       
      /**
        * @description The invoice number which acts as an identifier for invoice and is generated sequentially.

        */
       
      invoice_id:string;
       
      /**
        * @description The order status. \* cancelled - Order has been cancelled. Applicable only if you are using Chargebee&#x27;s legacy order management system \* new - Order has been created. Applicable only if you are using Chargebee&#x27;s legacy order management system. \* voided - Order has been voided. Applicable only if you are using Chargebee&#x27;s legacy order management system \* complete - Order has been processed successfully. Applicable only if you are using Chargebee&#x27;s legacy order management system \* processing - Order is being processed. Applicable only if you are using Chargebee&#x27;s legacy order management system

        */
       
      status?:'new' | 'processing' | 'cancelled' | 'voided' | 'complete';
       
      /**
        * @description Reference id can be used to map the orders in the shipping/order management application to the orders in ChargeBee. The reference_id generally is same as the order id in the third party application.

        */
       
      reference_id?:string;
       
      /**
        * @description The fulfillment status of an order as reflected in the shipping/order management application. Typical statuses include Shipped,Awaiting Shipment,Not fulfilled etc;.

        */
       
      fulfillment_status?:string;
       
      /**
        * @description The custom note for the order.

        */
       
      note?:string;
       
      /**
        * @description The tracking id of the order.

        */
       
      tracking_id?:string;
       
      /**
        * @description The tracking url of the order.

        */
       
      tracking_url?:string;
       
      /**
        * @description Unique id to identify a group of orders.

        */
       
      batch_id?:string;
    }
    export interface ImportOrderResponse {  
       order:Order;
    }
    export interface ImportOrderInputParam {
       
      /**
        * @description Uniquely identifies the order. It is the api identifier for the order.   

*Order id will always be assigned incrementally from the last generated Order ID.


If Orders imported has an Order ID which is a string, Chargebee will just validate if the Order ID is unique

Recommendation: For orders being imported, set the same prefix and the serial number that is used for the Document number, which will make this into a string. This will ensure that imported orders don&#x27;t conflict with orders created by Chargebee. Chargebee will ensure there aren&#x27;t orders with duplicate Order IDs.*.

        */
       
      id?:string;
       
      /**
        * @description The order&#x27;s serial number.   

*Document number passed cannot be greater than the series mentioned in the configuration. For instance, if you have set Document number series in Order Configurations with a Prefix as &#x27;ORDER&#x27; and Starting number as &#x27;1000&#x27;, orders up to the sequence number &#x27;ORDER999&#x27; can be imported into Chargebee*   

*Recommendation: Set a different prefix at the Order Configuration, than the ones that are imported. If your Order Configuration has a Prefix of &#x27;NEW&#x27;, with Starting number as &#x27;1&#x27;, i.e. &#x27;NEW1&#x27;, then, set Prefix for imported orders to be as &#x27;OLD&#x27;, with Starting number as &#x27;1&#x27;, i.e, &#x27;OLD1&#x27;*.

        */
       
      document_number?:string;
       
      /**
        * @description The invoice number which acts as an identifier for invoice and is generated sequentially.

        */
       
      invoice_id:string;
       
      /**
        * @description The status of this order. \* voided - Order has been voided. Applicable only if you are using Chargebee&#x27;s legacy order management system \* complete - Order has been processed successfully. Applicable only if you are using Chargebee&#x27;s legacy order management system \* shipped - The order has moved from order management system to a shipping system. \* processing - Order is being processed. Applicable only if you are using Chargebee&#x27;s legacy order management system \* queued - Order is yet to be processed by any system, these are scheduled orders created by Chargebee \* on_hold - The order is paused from being processed. \* new - Order has been created. Applicable only if you are using Chargebee&#x27;s legacy order management system. \* returned - The order has been returned after delivery. \* delivered - The order has been delivered to the customer. \* awaiting_shipment - The order has been picked up by an integration system, and synced to a shipping management platform \* cancelled - Order has been cancelled. Applicable only if you are using Chargebee&#x27;s legacy order management system \* partially_delivered - The order has been partially delivered to the customer.

        */
       
      status:'shipped' | 'partially_delivered' | 'queued' | 'cancelled' | 'delivered' | 'on_hold' | 'awaiting_shipment' | 'returned';
       
      /**
        * @description The subscription for which the order is created.

        */
       
      subscription_id?:string;
       
      /**
        * @description The customer for which the order is created.

        */
       
      customer_id?:string;
       
      /**
        * @description The time at which the order was created.

        */
       
      created_at:number;
       
      /**
        * @description The date on which the order will start getting processed.

        */
       
      order_date:number;
       
      /**
        * @description This is the date on which the order has to be shipped to the customer.

        */
       
      shipping_date:number;
       
      /**
        * @description Reference id can be used to map the orders in the shipping/order management application to the orders in ChargeBee. The reference_id generally is the same as the order id in the third party application.  

*Recommendation:

If this order is in any of these statuses, awaiting_shipment, on_hold, delivered, shipped, partially_delivered, returned, and has already been processed, through a 3rd party system, and you have a reference id of the entity in the 3rd party tool, pass in the entity id to this field. If not, set the same prefix and the serial number that is used for the Document number, which will make this into a string.*   

*If this order hasn&#x27;t been processed and is in &#x27;queued&#x27; status, do not pass any value to this field. Chargebee, when it syncs your Orders through the fulfilment integrations such as Shipstation or Shopify, would auto assign the reference id from the connected system.*.

        */
       
      reference_id?:string;
       
      /**
        * @description The fulfillment status of an order as reflected in the shipping/order management application. Typical statuses include Shipped,Awaiting Shipment,Not fulfilled etc;.   

*If this order is in any of these statuses, awaiting_shipment, on_hold, delivered, shipped, partially_delivered, returned, and has already been processed, through a 3rd party system, and you have a corresponding status from the 3rd party tool, pass in the status to this field.

If this order hasn&#x27;t been processed and is in &#x27;queued&#x27; status, do not pass any value to this field. Chargebee, when it syncs your Orders through the fulfilment integrations such as Shipstation or Shopify, would auto assign the fulfilment status from the connected system.*.

        */
       
      fulfillment_status?:string;
       
      /**
        * @description The custom note for the order.

        */
       
      note?:string;
       
      /**
        * @description The tracking id of the order.

        */
       
      tracking_id?:string;
       
      /**
        * @description The tracking url of the order.

        */
       
      tracking_url?:string;
       
      /**
        * @description Unique id to identify a group of orders.

        */
       
      batch_id?:string;
       
      /**
        * @description Shipment carrier.

        */
       
      shipment_carrier?:string;
       
      /**
        * @description The time after which an order becomes unservicable.

        */
       
      shipping_cut_off_date?:number;
       
      /**
        * @description The time at which the order was delivered.

        */
       
      delivered_at?:number;
       
      /**
        * @description The time at which the order was shipped.

        */
       
      shipped_at?:number;
       
      /**
        * @description The time at which the order was cancelled.

        */
       
      cancelled_at?:number;
       
      /**
        * @description Cancellation reason. \* shipping_cut_off_passed - The invoice has been paid late and Chargebee cancel&#x27;s the first order for the invoice. \* invoice_voided - The invoice for which the order was createed has been voided. \* alternative_found - Alternative found. \* others - Other reason \* order_resent - Order resent \* product_unsatisfactory - Product unsatisfactory. \* delivery_date_missed - Delivery date missed. \* subscription_cancelled - The subsctiption for which the order was created has been cancelled. \* fraudulent_transaction - Fraudulent transaction. \* invoice_written_off - The invoice has been completely written off. Orders are generated by Chargebee in cancelled state. \* product_not_required - Product not required. \* payment_declined - Payment declined. \* product_not_available - Product not available. \* third_party_cancellation - Third party cancellation.

        */
       
      cancellation_reason?:'delivery_date_missed' | 'subscription_cancelled' | 'product_unsatisfactory' | 'fraudulent_transaction' | 'third_party_cancellation' | 'order_resent' | 'payment_declined' | 'product_not_required' | 'invoice_voided' | 'invoice_written_off' | 'product_not_available' | 'shipping_cut_off_passed' | 'others' | 'alternative_found';
       
      /**
        * @description If there are any credits that were issued at the order level, you can make use of the field, refundable_credits_issued. This will lead to Chargebee creating a Refundable Credit note against the order. When the next invoice is raised against the customer, this credit note will be utilised.

        */
       
      refundable_credits_issued?:number;
       
      /**
        * @description Parameters for shipping_address

        */
       
      shipping_address?:{city?:string,company?:string,country?:string,email?:string,first_name?:string,last_name?:string,line1?:string,line2?:string,line3?:string,phone?:string,state?:string,state_code?:string,validation_status?:ValidationStatus,zip?:string};
       
      /**
        * @description Parameters for billing_address

        */
       
      billing_address?:{city?:string,company?:string,country?:string,email?:string,first_name?:string,last_name?:string,line1?:string,line2?:string,line3?:string,phone?:string,state?:string,state_code?:string,validation_status?:ValidationStatus,zip?:string};
    }
    export interface AssignOrderNumberResponse {  
       order:Order;
    }
    
    export interface ResendResponse {  
       order:Order;
    }
    export interface ResendInputParam {
       
      /**
        * @description The date on which the order should be shipped to the customer.

        */
       
      shipping_date?:number;
       
      /**
        * @description Reason code for resending the order. Must be one from a list of reason codes set in the Chargebee app in **Settings \&gt; Configure Chargebee \&gt; Reason Codes \&gt; Orders \&gt; Order Resend**. Must be passed if set as mandatory in the app. The codes are case-sensitive.

        */
       
      resend_reason?:string;
       
      /**
        * @description Parameters for order_line_items

        */
       
      order_line_items?:{fulfillment_quantity?:number,id?:string}[];
    }
    export interface ReopenResponse {  
       order:Order;
    }
    export interface ReopenInputParam {
       
      /**
        * @description Flag to void credit notes created for cancellation if they are unused.

        */
       
      void_cancellation_credit_notes?:boolean;
    }
    export interface CancelResponse {  
       order:Order;
    }
    export interface CancelInputParam {
       
      /**
        * @description Cancellation reason. \* shipping_cut_off_passed - The invoice has been paid late and Chargebee cancel&#x27;s the first order for the invoice. \* alternative_found - Alternative found. \* others - Other reason \* product_unsatisfactory - Product unsatisfactory. \* product_not_required - Product not required. \* delivery_date_missed - Delivery date missed. \* invoice_voided - The invoice for which the order was createed has been voided. \* payment_declined - Payment declined. \* product_not_available - Product not available. \* subscription_cancelled - The subsctiption for which the order was created has been cancelled. \* third_party_cancellation - Third party cancellation. \* fraudulent_transaction - Fraudulent transaction. \* order_resent - Order resent \* invoice_written_off - The invoice has been completely written off. Orders are generated by Chargebee in cancelled state.

        */
       
      cancellation_reason:'delivery_date_missed' | 'subscription_cancelled' | 'product_unsatisfactory' | 'fraudulent_transaction' | 'third_party_cancellation' | 'order_resent' | 'payment_declined' | 'product_not_required' | 'invoice_voided' | 'invoice_written_off' | 'product_not_available' | 'shipping_cut_off_passed' | 'others' | 'alternative_found';
       
      /**
        * @description The Customer Notes to be filled in the Credit Notes created to capture this refund detail.

        */
       
      customer_notes?:string;
       
      /**
        * @description Comment, if any, on the refund.

        */
       
      comment?:string;
       
      /**
        * @description The time at which the order was cancelled.

        */
       
      cancelled_at?:number;
       
      /**
        * @description Parameters for credit_note

        */
       
      credit_note?:{total?:number};
    }
    export interface RetrieveResponse {  
       order:Order;
    }
    
    export interface UpdateResponse {  
       order:Order;
    }
    export interface UpdateInputParam {
       
      /**
        * @description Reference id is the unique identifier of the order in the shipping/order management application.

        */
       
      reference_id?:string;
       
      /**
        * @description Unique id to identify a group of orders.

        */
       
      batch_id?:string;
       
      /**
        * @description The custom note for the order.

        */
       
      note?:string;
       
      /**
        * @description The date on which the order should be shipped to the customer.

        */
       
      shipping_date?:number;
       
      /**
        * @description The order date.

        */
       
      order_date?:number;
       
      /**
        * @description The time at which the order was cancelled.

        */
       
      cancelled_at?:number;
       
      /**
        * @description Cancellation reason. \* shipping_cut_off_passed - The invoice has been paid late and Chargebee cancel&#x27;s the first order for the invoice. \* invoice_voided - The invoice for which the order was createed has been voided. \* alternative_found - Alternative found. \* others - Other reason \* order_resent - Order resent \* product_unsatisfactory - Product unsatisfactory. \* delivery_date_missed - Delivery date missed. \* subscription_cancelled - The subsctiption for which the order was created has been cancelled. \* fraudulent_transaction - Fraudulent transaction. \* invoice_written_off - The invoice has been completely written off. Orders are generated by Chargebee in cancelled state. \* product_not_required - Product not required. \* payment_declined - Payment declined. \* product_not_available - Product not available. \* third_party_cancellation - Third party cancellation.

        */
       
      cancellation_reason?:'delivery_date_missed' | 'subscription_cancelled' | 'product_unsatisfactory' | 'fraudulent_transaction' | 'third_party_cancellation' | 'order_resent' | 'payment_declined' | 'product_not_required' | 'invoice_voided' | 'invoice_written_off' | 'product_not_available' | 'shipping_cut_off_passed' | 'others' | 'alternative_found';
       
      /**
        * @description The time at which the order was shipped.

        */
       
      shipped_at?:number;
       
      /**
        * @description The time at which the order was delivered.

        */
       
      delivered_at?:number;
       
      /**
        * @description The tracking url of the order.

        */
       
      tracking_url?:string;
       
      /**
        * @description The tracking id of the order.

        */
       
      tracking_id?:string;
       
      /**
        * @description The carrier used to ship the goods to the customer. Ex:- FedEx.

        */
       
      shipment_carrier?:string;
       
      /**
        * @description The fulfillment status of an order as reflected in the shipping/order management application. Typical statuses include Shipped,Awaiting Shipment,Not fulfilled etc;.

        */
       
      fulfillment_status?:string;
       
      /**
        * @description The order status. \* voided - Order has been voided. Applicable only if you are using Chargebee&#x27;s legacy order management system \* complete - Order has been processed successfully. Applicable only if you are using Chargebee&#x27;s legacy order management system \* shipped - The order has moved from order management system to a shipping system. \* processing - Order is being processed. Applicable only if you are using Chargebee&#x27;s legacy order management system \* queued - Order is yet to be processed by any system, these are scheduled orders created by Chargebee \* on_hold - The order is paused from being processed. \* new - Order has been created. Applicable only if you are using Chargebee&#x27;s legacy order management system. \* returned - The order has been returned after delivery. \* delivered - The order has been delivered to the customer. \* awaiting_shipment - The order has been picked up by an integration system, and synced to a shipping management platform \* cancelled - Order has been cancelled. Applicable only if you are using Chargebee&#x27;s legacy order management system \* partially_delivered - The order has been partially delivered to the customer.

        */
       
      status?:'new' | 'partially_delivered' | 'queued' | 'delivered' | 'on_hold' | 'shipped' | 'processing' | 'cancelled' | 'voided' | 'complete' | 'awaiting_shipment' | 'returned';
       
      /**
        * @description Parameters for shipping_address

        */
       
      shipping_address?:{city?:string,company?:string,country?:string,email?:string,first_name?:string,last_name?:string,line1?:string,line2?:string,line3?:string,phone?:string,state?:string,state_code?:string,validation_status?:ValidationStatus,zip?:string};
       
      /**
        * @description Parameters for order_line_items

        */
       
      order_line_items?:{id?:string,sku?:string,status?:'shipped' | 'partially_delivered' | 'queued' | 'cancelled' | 'delivered' | 'on_hold' | 'awaiting_shipment' | 'returned'}[];
    }
    export interface DeleteResponse {  
       order:Order;
    }
    
    export interface CreateRefundableCreditNoteResponse {  
       order:Order;
    }
    export interface CreateRefundableCreditNoteInputParam {
       
      /**
        * @description The Customer Notes to be filled in the Credit Notes created to capture this refund detail.

        */
       
      customer_notes?:string;
       
      /**
        * @description Comment, if any, on the refund.

        */
       
      comment?:string;
       
      /**
        * @description Parameters for credit_note

        */
       
      credit_note?:{reason_code:'other' | 'product_unsatisfactory' | 'subscription_pause' | 'order_cancellation' | 'service_unsatisfactory' | 'subscription_cancellation' | 'chargeback' | 'order_change' | 'write_off' | 'waiver' | 'subscription_change' | 'fraudulent',total:number};
    }
    export interface OrderLineItem {  
      id?:string;
       
      invoice_id?:string;
       
      invoice_line_item_id?:string;
       
      unit_price?:number;
       
      description?:string;
       
      amount?:number;
       
      fulfillment_quantity?:number;
       
      fulfillment_amount?:number;
       
      tax_amount?:number;
       
      amount_paid?:number;
       
      amount_adjusted?:number;
       
      refundable_credits_issued?:number;
       
      refundable_credits?:number;
       
      is_shippable?:boolean;
       
      sku?:string;
       
      status?:'shipped' | 'partially_delivered' | 'queued' | 'cancelled' | 'delivered' | 'on_hold' | 'awaiting_shipment' | 'returned';
       
      entity_type?:'addon_item_price' | 'plan_item_price' | 'charge_item_price' | 'adhoc';
       
      item_level_discount_amount?:number;
       
      discount_amount?:number;
       
      entity_id?:string;
    }
    export interface ShippingAddress {  
         /**
          * @description The first name of the contact.

          */
       
      first_name?:string;
       
         /**
          * @description The last name of the contact.

          */
       
      last_name?:string;
       
         /**
          * @description The email address.

          */
       
      email?:string;
       
         /**
          * @description The company name.

          */
       
      company?:string;
       
         /**
          * @description The phone number.

          */
       
      phone?:string;
       
         /**
          * @description Address line 1

          */
       
      line1?:string;
       
         /**
          * @description Address line 2

          */
       
      line2?:string;
       
         /**
          * @description Address line 3

          */
       
      line3?:string;
       
         /**
          * @description The name of the city.

          */
       
      city?:string;
       
         /**
          * @description The [ISO 3166-2 state/province code](https://www.iso.org/obp/ui/#search) without the country prefix. Currently supported for USA, Canada and India. For instance, for Arizona (USA), set &#x60;state_code&#x60; as &#x60;AZ&#x60; (not &#x60;US-AZ&#x60;). For Tamil Nadu (India), set as &#x60;TN&#x60; (not &#x60;IN-TN&#x60;). For British Columbia (Canada), set as &#x60;BC&#x60; (not &#x60;CA-BC&#x60;).

          */
       
      state_code?:string;
       
         /**
          * @description The state/province name.

          */
       
      state?:string;
       
         /**
          * @description The billing address country of the customer. Must be one of [ISO 3166 alpha-2 country code](https://www.iso.org/iso-3166-country-codes.html).   

**Note** : If you enter an invalid country code, the system will return an error.  

**Brexit**


If you have enabled [EU VAT](https://www.chargebee.com/docs/eu-vat.html) in 2021 or later, or have [manually enable](https://www.chargebee.com/docs/brexit.html#what-needs-to-be-done-in-chargebee) the Brexit configuration, then &#x60;XI&#x60; (the code for **United Kingdom -- Northern Ireland**) is available as an option.

          */
       
      country?:string;
       
         /**
          * @description Zip or postal code. The number of characters is validated according to the rules [specified here](https://chromium-i18n.appspot.com/ssl-address).

          */
       
      zip?:string;
       
         /**
          * @description The address verification status. \* not_validated - Address is not yet validated. \* valid - Address was validated successfully. \* partially_valid - The address is valid for taxability but has not been validated for shipping. \* invalid - Address is invalid.

          */
       
      validation_status?:ValidationStatus;
       
         /**
          * @description The index number of the subscription to which the item price is added. Provide a unique number between &#x60;0&#x60; and &#x60;4&#x60; (inclusive) for each subscription that is to be created.

          */
       
      index?:number;
    }
    export interface BillingAddress {  
         /**
          * @description The first name of the billing contact.

          */
       
      first_name?:string;
       
         /**
          * @description The last name of the billing contact.

          */
       
      last_name?:string;
       
         /**
          * @description The email address.

          */
       
      email?:string;
       
         /**
          * @description The company name.

          */
       
      company?:string;
       
         /**
          * @description The phone number.

          */
       
      phone?:string;
       
         /**
          * @description Address line 1

          */
       
      line1?:string;
       
         /**
          * @description Address line 2

          */
       
      line2?:string;
       
         /**
          * @description Address line 3

          */
       
      line3?:string;
       
         /**
          * @description The name of the city.

          */
       
      city?:string;
       
         /**
          * @description The [ISO 3166-2 state/province code](https://www.iso.org/obp/ui/#search) without the country prefix. Currently supported for USA, Canada and India. For instance, for Arizona (USA), set &#x60;state_code&#x60; as &#x60;AZ&#x60; (not &#x60;US-AZ&#x60;). For Tamil Nadu (India), set as &#x60;TN&#x60; (not &#x60;IN-TN&#x60;). For British Columbia (Canada), set as &#x60;BC&#x60; (not &#x60;CA-BC&#x60;).

          */
       
      state_code?:string;
       
         /**
          * @description State or Province

          */
       
      state?:string;
       
         /**
          * @description The billing address country of the customer. Must be one of [ISO 3166 alpha-2 country code](https://www.iso.org/iso-3166-country-codes.html).   

**Note** : If you enter an invalid country code, the system will return an error.  

**Brexit**


If you have enabled [EU VAT](https://www.chargebee.com/docs/eu-vat.html) in 2021 or later, or have [manually enable](https://www.chargebee.com/docs/brexit.html#what-needs-to-be-done-in-chargebee) the Brexit configuration, then &#x60;XI&#x60; (the code for **United Kingdom -- Northern Ireland**) is available as an option.

          */
       
      country?:string;
       
         /**
          * @description Zip or postal code. The number of characters is validated according to the rules [specified here](https://chromium-i18n.appspot.com/ssl-address).

          */
       
      zip?:string;
       
         /**
          * @description The address verification status. \* valid - Address was validated successfully. \* partially_valid - The address is valid for taxability but has not been validated for shipping. \* invalid - Address is invalid. \* not_validated - Address is not yet validated.

          */
       
      validation_status?:ValidationStatus;
    }
    export interface LineItemTax {  
      line_item_id?:string;
       
      tax_name?:string;
       
      tax_rate?:number;
       
      is_partial_tax_applied?:boolean;
       
      is_non_compliance_tax?:boolean;
       
      taxable_amount?:number;
       
      tax_amount?:number;
       
      tax_juris_type?:'special' | 'country' | 'unincorporated' | 'other' | 'city' | 'federal' | 'county' | 'state';
       
      tax_juris_name?:string;
       
      tax_juris_code?:string;
       
      tax_amount_in_local_currency?:number;
       
      local_currency_code?:string;
    }
    export interface LineItemDiscount {  
      line_item_id?:string;
       
      discount_type?:'custom_discount' | 'item_level_coupon' | 'promotional_credits' | 'item_level_discount' | 'prorated_credits' | 'document_level_discount' | 'document_level_coupon';
       
      entity_id?:string;
       
      discount_amount?:number;
    }
    export interface OrderLineItemLinkedCredit {  
      amount?:number;
       
      type?:'adjustment' | 'refundable';
       
      id?:string;
       
      status?:'refund_due' | 'adjusted' | 'refunded' | 'voided';
       
      amount_adjusted?:number;
       
      amount_refunded?:number;
    }
    export interface ResentOrder {  
      order_id?:string;
       
      reason?:string;
       
      amount?:number;
    }
  }
}