///<reference path='./../core.d.ts'/>
declare module 'chargebee' {
  export interface Usage {
    
    /**
      * @description A unique and immutable id for the usage. If not provided, it is autogenerated.

      */
    
    id?:string;
    
    /**
      * @description The time at which this usage occurred. Chargebee bills only those usages whose &#x60;usage_date&#x60; falls within a time when the subscription &#x60;status&#x60; was &#x60;active&#x60; or &#x60;non_renewing&#x60;. However, the remaining usage records are still stored and are [retrievable](/docs/api/usages?prod_cat_ver&#x3D;2#retrieve_a_usage).   
**Note:** If &#x60;usage_date&#x60; corresponds to a time already invoiced, then it is stored but never invoiced unless the [invoice is regenerated](/docs/api/subscriptions?prod_cat_ver&#x3D;2#regenerate_an_invoice).

      */
    
    usage_date:number;
    
    /**
      * @description The id of the [subscription](/docs/api/subscriptions?prod_cat_ver&#x3D;2) to which this usage record belongs.

      */
    
    subscription_id:string;
    
    /**
      * @description The id of the [item price](/docs/api/item_prices?prod_cat_ver&#x3D;2) to which this usage belongs. The item price must be a part of the subscription or should have been part of it historically.

      */
    
    item_price_id:string;
    
    /**
      * @description When the usage has been invoiced, this is the &#x60;id&#x60; of the [invoice](/docs/api/invoices?prod_cat_ver&#x3D;2). This is cleared when the invoice is &#x60;voided&#x60; or deleted.

      */
    
    invoice_id?:string;
    
    /**
      * @description When the usage has been invoiced, this is the &#x60;id&#x60; of the [invoice.line_item](/docs/api/invoices?prod_cat_ver&#x3D;2#invoice_line_items) that the usage is for. This is cleared when the invoice is [voided](/docs/api/invoices?prod_cat_ver&#x3D;2#void_an_invoice) or [deleted](/docs/api/invoices?prod_cat_ver&#x3D;2#delete_an_invoice).

      */
    
    line_item_id?:string;
    
    /**
      * @description The quantity specified for this usage record.

      */
    
    quantity:string;
    
    /**
      * @description The source from which the usage record was created. \* admin_console - Operation made through the Chargebee admin UI \* api - Operation made through the API \* bulk_operation - Operation that are triggerd through bulk operation.

      */
    
    source?:Source;
    
    /**
      * @description A note for this usage record. This appears against the usage on the Chargebee UI. This note is not displayed on any customer-facing document or interface such as [invoice PDFs](/docs/api/invoices?prod_cat_ver&#x3D;2#retrieve_invoice_as_pdf) or [Hosted Pages](/docs/api/hosted_pages?prod_cat_ver&#x3D;2).

      */
    
    note?:string;
    
    /**
      * @description Version number of this resource. The &#x60;resource_version&#x60; is updated with a new timestamp in milliseconds for every change made to the resource. This attribute will be present only if the resource has been updated after 2016-09-28.

      */
    
    resource_version?:number;
    
    /**
      * @description Timestamp indicating when this usage resource was last updated.

      */
    
    updated_at?:number;
    
    /**
      * @description Timestamp indicating when the item was created.

      */
    
    created_at:number;
  }
  export namespace Usage {
    export class UsageResource {  
      /**
        * @description Creates a usage record for an item price in a subscription. The item price must belong to a [metered](/docs/api/items?prod_cat_ver&#x3D;2#item_metered) item.  
**Max Usages**   
The maximum number of usages that can be recorded for the entire lifetime of a subscription is 5000. [Contact Support](https://chargebee.freshdesk.com/support/home) if you want this limit to be increased for your site.

        */
      
      create(subscription_id:string, input:CreateInputParam):ChargebeeRequest<CreateResponse>;
       
      /**
        * @description Retrieves a usage record of a specific subscription.

        */
      
      retrieve(subscription_id:string, input:RetrieveInputParam):ChargebeeRequest<RetrieveResponse>;
       
      /**
        * @description Deletes a usage record. This operation cannot be invoked for a usage record that has been [invoiced](usages?prod_cat_ver&#x3D;2#invoicing_usages).

        */
      
      delete(subscription_id:string, input:DeleteInputParam):ChargebeeRequest<DeleteResponse>;
       
      /**
        * @description Retrieves the list of usages.

        */
      
      list(input:ListInputParam):ChargebeeRequest<ListResponse>;
       
      /**
        * @description Retrieves usages record for an invoice in PDF file format.

        */
      
      pdf(input?:PdfInputParam):ChargebeeRequest<PdfResponse>;
    }
    export interface CreateResponse {  
       usage:Usage;
    }
    export interface CreateInputParam {
       
      /**
        * @description A unique and immutable id for the usage. If not provided, it is autogenerated.

        */
       
      id?:string;
       
      /**
        * @description The id of the [item price](/docs/api/item_prices?prod_cat_ver&#x3D;2) to which this usage belongs. The item price must be a part of the subscription or should have been part of it historically.

        */
       
      item_price_id:string;
       
      /**
        * @description The quantity specified for this usage record.

        */
       
      quantity:string;
       
      /**
        * @description The time at which this usage occurred. Chargebee bills only those usages whose &#x60;usage_date&#x60; falls within a time when the subscription &#x60;status&#x60; was &#x60;active&#x60; or &#x60;non_renewing&#x60;. However, the remaining usage records are still stored and are [retrievable](/docs/api/usages?prod_cat_ver&#x3D;2#retrieve_a_usage).   
**Note:** If &#x60;usage_date&#x60; corresponds to a time already invoiced, then it is stored but never invoiced unless the [invoice is regenerated](/docs/api/subscriptions?prod_cat_ver&#x3D;2#regenerate_an_invoice).

        */
       
      usage_date:number;
       
      /**
        * @description A note for this usage record. This appears against the usage on the Chargebee UI. This note is not displayed on any customer-facing document or interface such as [invoice PDFs](/docs/api/invoices?prod_cat_ver&#x3D;2#retrieve_invoice_as_pdf) or [Hosted Pages](/docs/api/hosted_pages?prod_cat_ver&#x3D;2).

        */
       
      note?:string;
    }
    export interface RetrieveResponse {  
       usage:Usage;
    }
    export interface RetrieveInputParam {
       
      /**
        * @description Retrieves a usage record of a specific subscription.

        */
        
      id:string;
    }
    export interface DeleteResponse {  
       usage:Usage;
    }
    export interface DeleteInputParam {
       
      /**
        * @description A unique and immutable id for the usage. If not provided, it is autogenerated.

        */
       
      id:string;
    }
    export interface ListResponse {  
      /**
        * @description Retrieves the list of usages.

        */
       
       list:{usage:Usage}[];
       
      /**
        * @description Retrieves the list of usages.

        */
       
       next_offset?:string;
    }
    export interface ListInputParam {
      [key : string]: any;  
      /**
        * @description Retrieves the list of usages.

        */
        
      limit?:number;
       
      /**
        * @description Retrieves the list of usages.

        */
        
      offset?:string;
       
      /**
        * @description Retrieves the list of usages.

        */
        
      id?:{is?:string,is_not?:string,starts_with?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      subscription_id:{is?:string,is_not?:string,starts_with?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      usage_date?:{after?:string,before?:string,between?:string,on?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      item_price_id?:{is?:string,is_not?:string,starts_with?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      invoice_id?:{is?:string,is_not?:string,is_present?:'true' | 'false',starts_with?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      source?:{in?:string,is?:'admin_console' | 'bulk_operation' | 'api',is_not?:'admin_console' | 'bulk_operation' | 'api',not_in?:string};
       
      /**
        * @description Retrieves the list of usages.

        */
        
      sort_by?:{asc?:'usage_date',desc?:'usage_date'};
    }
    export interface PdfResponse {  
       download:Download;
    }
    export interface PdfInputParam {
       
      /**
        * @description Determines the pdf should be rendered as inline or attachment in the browser. \* attachment - PDF is rendered as attachment in the browser \* inline - PDF is rendered as inline in the browser

        */
       
      disposition_type?:DispositionType;
       
      /**
        * @description Parameters for invoice

        */
       
      invoice?:{id:string};
    }
    
  }
}