// Generated Zod validator: PaymentSource.createUsingTempToken
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const createUsingTempTokenPaymentSourceAdditionalInformationSchema =
  z.looseObject({});
const createUsingTempTokenPaymentSourceBodySchema = z.looseObject({
  customer_id: z.string().max(50),
  gateway_account_id: z.string().max(50).optional(),
  type: z.enum([
    'card',
    'paypal_express_checkout',
    'amazon_payments',
    'direct_debit',
    'generic',
    'alipay',
    'unionpay',
    'apple_pay',
    'wechat_pay',
    'ideal',
    'google_pay',
    'sofort',
    'bancontact',
    'giropay',
    'dotpay',
    'upi',
    'netbanking_emandates',
    'venmo',
    'pay_to',
    'faster_payments',
    'sepa_instant_transfer',
    'automated_bank_transfer',
    'klarna_pay_now',
    'online_banking_poland',
    'payconiq_by_bancontact',
    'electronic_payment_standard',
    'kbc_payment_button',
    'pay_by_bank',
    'trustly',
    'stablecoin',
    'kakao_pay',
    'naver_pay',
    'revolut_pay',
    'cash_app_pay',
    'pix',
    'twint',
    'go_pay',
    'grab_pay',
    'pay_co',
    'after_pay',
    'swish',
    'payme',
  ]),
  tmp_token: z.string().max(65000),
  issuing_country: z.string().max(50).optional(),
  replace_primary_payment_source: z.boolean().default(false).optional(),
  additional_information:
    createUsingTempTokenPaymentSourceAdditionalInformationSchema.optional(),
});
export { createUsingTempTokenPaymentSourceBodySchema };
