// Generated Zod validator: PaymentSource.createUsingPermanentToken
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const createUsingPermanentTokenPaymentSourceAdditionalInformationSchema =
  z.looseObject({});
const createUsingPermanentTokenPaymentSourceCardSchema = z.object({
  last4: z.string().max(4).min(4).optional(),
  iin: z.string().max(6).min(6).optional(),
  expiry_month: z.number().int().min(1).max(12).optional(),
  expiry_year: z.number().int().optional(),
  brand: z
    .enum([
      'visa',
      'mastercard',
      'american_express',
      'discover',
      'jcb',
      'diners_club',
      'other',
      'bancontact',
      'cmr_falabella',
      'tarjeta_naranja',
      'nativa',
      'cencosud',
      'cabal',
      'argencard',
      'elo',
      'hipercard',
      'carnet',
      'rupay',
      'maestro',
      'dankort',
      'cartes_bancaires',
      'mada',
    ])
    .optional(),
  funding_type: z.enum(['credit', 'debit', 'prepaid', 'not_known']).optional(),
});
const createUsingPermanentTokenPaymentSourceBillingAddressSchema = z.object({
  first_name: z.string().max(150).optional(),
  last_name: z.string().max(150).optional(),
  email: z.string().email().max(70).optional(),
  line1: z.string().max(150).optional(),
  line2: z.string().max(150).optional(),
  line3: z.string().max(150).optional(),
  city: z.string().max(50).optional(),
  state_code: z.string().max(50).optional(),
  state: z.string().max(50).optional(),
  zip: z.string().max(20).optional(),
  country: z.string().max(50).optional(),
});
const createUsingPermanentTokenPaymentSourceBodySchema = z.looseObject({
  customer_id: z.string().max(50),
  type: z.enum([
    'card',
    'paypal_express_checkout',
    'amazon_payments',
    'direct_debit',
    'generic',
    'alipay',
    'unionpay',
    'apple_pay',
    'wechat_pay',
    'ideal',
    'google_pay',
    'sofort',
    'bancontact',
    'giropay',
    'dotpay',
    'upi',
    'netbanking_emandates',
    'venmo',
    'pay_to',
    'faster_payments',
    'sepa_instant_transfer',
    'automated_bank_transfer',
    'klarna_pay_now',
    'online_banking_poland',
    'payconiq_by_bancontact',
    'electronic_payment_standard',
    'kbc_payment_button',
    'pay_by_bank',
    'trustly',
    'stablecoin',
    'kakao_pay',
    'naver_pay',
    'revolut_pay',
    'cash_app_pay',
    'pix',
    'twint',
    'go_pay',
    'grab_pay',
    'pay_co',
    'after_pay',
    'swish',
    'payme',
  ]),
  gateway_account_id: z.string().max(50).optional(),
  reference_id: z.string().max(200).optional(),
  issuing_country: z.string().max(50).optional(),
  replace_primary_payment_source: z.boolean().default(false).optional(),
  payment_method_token: z.string().max(100).optional(),
  customer_profile_token: z.string().max(100).optional(),
  network_transaction_id: z.string().max(100).optional(),
  mandate_id: z.string().max(100).optional(),
  skip_retrieval: z.boolean().default(false).optional(),
  additional_information:
    createUsingPermanentTokenPaymentSourceAdditionalInformationSchema.optional(),
  card: createUsingPermanentTokenPaymentSourceCardSchema.optional(),
  billing_address:
    createUsingPermanentTokenPaymentSourceBillingAddressSchema.optional(),
});
export { createUsingPermanentTokenPaymentSourceBodySchema };
