// Generated Zod validator: Customer.collectPayment
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const collectPaymentCustomerAdditionalInformationSchema = z.looseObject({});
const collectPaymentCustomerPaymentMethodSchema = z.object({
  type: z
    .enum([
      'card',
      'paypal_express_checkout',
      'amazon_payments',
      'direct_debit',
      'generic',
      'alipay',
      'unionpay',
      'apple_pay',
      'wechat_pay',
      'ideal',
      'google_pay',
      'sofort',
      'bancontact',
      'giropay',
      'dotpay',
      'upi',
      'netbanking_emandates',
      'venmo',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'automated_bank_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
  gateway_account_id: z.string().max(50).optional(),
  reference_id: z.string().max(200).optional(),
  tmp_token: z.string().max(65000).optional(),
  additional_information:
    collectPaymentCustomerAdditionalInformationSchema.optional(),
});
const collectPaymentCustomerCardSchema = z.object({
  gateway_account_id: z.string().max(50).optional(),
  first_name: z.string().max(50).optional(),
  last_name: z.string().max(50).optional(),
  number: z.string().max(1500).optional(),
  expiry_month: z.number().int().min(1).max(12).optional(),
  expiry_year: z.number().int().optional(),
  cvv: z.string().max(520).optional(),
  preferred_scheme: z
    .enum(['cartes_bancaires', 'mastercard', 'visa'])
    .optional(),
  billing_addr1: z.string().max(150).optional(),
  billing_addr2: z.string().max(150).optional(),
  billing_city: z.string().max(50).optional(),
  billing_state_code: z.string().max(50).optional(),
  billing_state: z.string().max(50).optional(),
  billing_zip: z.string().max(20).optional(),
  billing_country: z.string().max(50).optional(),
  additional_information:
    collectPaymentCustomerAdditionalInformationSchema.optional(),
});
const collectPaymentCustomerPaymentIntentSchema = z.object({
  id: z.string().max(150).optional(),
  gateway_account_id: z.string().max(50).optional(),
  gw_token: z.string().max(65000).optional(),
  payment_method_type: z
    .enum([
      'card',
      'ideal',
      'sofort',
      'bancontact',
      'google_pay',
      'dotpay',
      'giropay',
      'apple_pay',
      'upi',
      'netbanking_emandates',
      'paypal_express_checkout',
      'direct_debit',
      'boleto',
      'venmo',
      'amazon_payments',
      'pay_to',
      'faster_payments',
      'sepa_instant_transfer',
      'klarna_pay_now',
      'online_banking_poland',
      'payconiq_by_bancontact',
      'electronic_payment_standard',
      'kbc_payment_button',
      'pay_by_bank',
      'trustly',
      'stablecoin',
      'kakao_pay',
      'naver_pay',
      'revolut_pay',
      'cash_app_pay',
      'wechat_pay',
      'alipay',
      'pix',
      'twint',
      'go_pay',
      'grab_pay',
      'pay_co',
      'after_pay',
      'swish',
      'payme',
    ])
    .optional(),
  gw_payment_method_id: z.string().max(65000).optional(),
  reference_id: z.string().max(65000).optional(),
  additional_information:
    collectPaymentCustomerAdditionalInformationSchema.optional(),
});
const collectPaymentCustomerInvoiceAllocationsSchema = z.object({
  invoice_id: z.array(z.string().max(50).optional()),
  allocation_amount: z.array(z.number().int().min(0).optional()).optional(),
});
const collectPaymentCustomerBodySchema = z.looseObject({
  amount: z.number().int().min(0).optional(),
  payment_source_id: z.string().max(40).optional(),
  token_id: z.string().max(40).optional(),
  replace_primary_payment_source: z.boolean().default(false).optional(),
  retain_payment_source: z.boolean().default(false).optional(),
  payment_initiator: z.enum(['customer', 'merchant']).optional(),
  payment_method: collectPaymentCustomerPaymentMethodSchema.optional(),
  card: collectPaymentCustomerCardSchema.optional(),
  payment_intent: collectPaymentCustomerPaymentIntentSchema.optional(),
  invoice_allocations:
    collectPaymentCustomerInvoiceAllocationsSchema.optional(),
});
export { collectPaymentCustomerBodySchema };
