// Generated Zod validator: Customer.updatePaymentMethod
// Do not edit manually – regenerate via sdk-generator

import { z } from 'zod';
const updatePaymentMethodCustomerAdditionalInformationSchema = z.looseObject(
  {},
);
const updatePaymentMethodCustomerPaymentMethodSchema = z.object({
  type: z.enum([
    'card',
    'paypal_express_checkout',
    'amazon_payments',
    'direct_debit',
    'generic',
    'alipay',
    'unionpay',
    'wechat_pay',
    'ideal',
    'google_pay',
    'sofort',
    'bancontact',
    'giropay',
    'dotpay',
    'upi',
    'netbanking_emandates',
    'venmo',
    'pay_to',
    'faster_payments',
    'sepa_instant_transfer',
    'automated_bank_transfer',
    'klarna_pay_now',
    'online_banking_poland',
    'payconiq_by_bancontact',
    'electronic_payment_standard',
    'kbc_payment_button',
    'pay_by_bank',
    'trustly',
    'stablecoin',
    'kakao_pay',
    'naver_pay',
    'revolut_pay',
    'cash_app_pay',
    'pix',
    'twint',
    'go_pay',
    'grab_pay',
    'pay_co',
    'after_pay',
    'swish',
    'payme',
  ]),
  gateway: z
    .enum([
      'chargebee_payments',
      'adyen',
      'stripe',
      'wepay',
      'braintree',
      'authorize_net',
      'paypal_pro',
      'pin',
      'eway',
      'eway_rapid',
      'worldpay',
      'balanced_payments',
      'beanstream',
      'bluepay',
      'elavon',
      'first_data_global',
      'hdfc',
      'migs',
      'nmi',
      'ogone',
      'paymill',
      'paypal_payflow_pro',
      'sage_pay',
      'tco',
      'wirecard',
      'amazon_payments',
      'paypal_express_checkout',
      'gocardless',
      'orbital',
      'moneris_us',
      'moneris',
      'bluesnap',
      'cybersource',
      'vantiv',
      'checkout_com',
      'paypal',
      'ingenico_direct',
      'exact',
      'mollie',
      'quickbooks',
      'razorpay',
      'global_payments',
      'bank_of_america',
      'ecentric',
      'metrics_global',
      'windcave',
      'pay_com',
      'ebanx',
      'dlocal',
      'nuvei',
      'solidgate',
      'paystack',
      'jp_morgan',
      'deutsche_bank',
      'ezidebit',
      'twikey',
      'tempus',
      'moyasar',
      'payway',
    ])
    .optional(),
  gateway_account_id: z.string().max(50).optional(),
  reference_id: z.string().max(200).optional(),
  tmp_token: z.string().max(65000).optional(),
  issuing_country: z.string().max(50).optional(),
  additional_information:
    updatePaymentMethodCustomerAdditionalInformationSchema.optional(),
});
const updatePaymentMethodCustomerBodySchema = z.looseObject({
  payment_method: updatePaymentMethodCustomerPaymentMethodSchema.optional(),
});
export { updatePaymentMethodCustomerBodySchema };
